### ISSUE TITLE
.DS_Store file under storage is fatal

### ISSUE THREAD

**Issue by joneskoo** [hlandau/acme#101]
After accessing certs directory with Finder, I got this:

```
$ ./acmetool unwant tlstest.yx.fi
20160131221553 [CRITICAL] acmetool: fatal: storage: lstat /usr/local/var/lib/acmetool/certs/.DS_Store/url: not a directory
```

Finder creates .DS_Store files all around, like Windows does Thumbs.db. I believe acmetool should either ignore or destroy the file, and not consider it fatal. Maybe it's enough to just check if it is a directory before expecting it to be?

**Comment by hlandau** [comment]
Fixed.
