### ISSUE TITLE
Acmetool Crashes On "want" When Not Doing Quickstart First

### ISSUE THREAD

**Issue by thomaskonrad** [hlandau/acme#102]
Hi,

when issuing ```acmetool want mydomain.com``` without doing ```acmetool quickstart``` first, it crashes with a segfault-like error message:

    root@example:/etc/apache2# acmetool want mydomain.com
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x53ccb5]

    goroutine 1 [running]:
    github.com/hlandau/acme/storageops.(*reconcile).requestCertificateForTarget(0xc820136b40, 0xc820160480, 0x0, 0x0)
            /home/travis/gopath/src/github.com/hlandau/acme/storageops/reconcile.go:546 +0xa15
    github.com/hlandau/acme/storageops.(*reconcile).processTargets.func1(0xc820160480, 0x0, 0x0)
            /home/travis/gopath/src/github.com/hlandau/acme/storageops/reconcile.go:521 +0x411
    github.com/hlandau/acme/storage.(*fdbStore).VisitTargets(0xc820162480, 0xc82015f080, 0x0, 0x0)
            /home/travis/gopath/src/github.com/hlandau/acme/storage/storage-fdb.go:88 +0x98
    github.com/hlandau/acme/storageops.(*reconcile).processTargets(0xc820136b40, 0x0, 0x0)
            /home/travis/gopath/src/github.com/hlandau/acme/storageops/reconcile.go:533 +0xdd
    github.com/hlandau/acme/storageops.(*reconcile).Reconcile(0xc820136b40, 0x0, 0x0)
            /home/travis/gopath/src/github.com/hlandau/acme/storageops/reconcile.go:150 +0x1a7
    github.com/hlandau/acme/storageops.Reconcile(0x7fa604f9a260, 0xc820162480, 0x0, 0x0)
            /home/travis/gopath/src/github.com/hlandau/acme/storageops/reconcile.go:56 +0x8a
    main.cmdReconcile()
            /home/travis/gopath/src/github.com/hlandau/acme/cmd/acmetool/main.go:189 +0x181
    main.main()
            /home/travis/gopath/src/github.com/hlandau/acme/cmd/acmetool/main.go:136 +0x47b

    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
            /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

    goroutine 5 [syscall]:
    os/signal.loop()
            /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
    created by os/signal.init.1
            /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

I've seen this on a Ubuntu 14.04.3 LTS server. It would be nice to see something like "Please use ```quickstart``` first" instead.

Thanks
Tom

**Comment by hlandau** [comment]
A bug matching this description was fixed recently in master. I've released v0.0.44. Please try it.
