### ISSUE TITLE
DNS challenge want tries to open webroot file

### ISSUE THREAD

**Issue by jmhodges** [hlandau/acme#103]
Setting up with HOOKS, and the DNS challenge, and then calling `want` causes a webroot path to be opened. 

This error log shows up:

    20160202004528 [ERROR] acme.responder: failed to open webroot file /var/run/acme/acme-challenge/FB11bxA3wIfyoyE1zy_bFDT_3BWbEJphOOQqbel9BCU: open /var/run/acme/acme-challenge/FB11bxA3wIfyoyE1zy_bFDT_3BWbEJphOOQqbel9BCU: no such file or directory

It shouldn't since the DNS challenge doesn't need a webroot path.

**Comment by hlandau** [comment]
Please see https://hlandau.github.io/acme/userguide#challenge-completion-philosophy

**Comment by jmhodges** [comment]
Ah, okay, sorry.
