### ISSUE TITLE
Make fails on Amazon Linux with:  undefined: elliptic.P224

### ISSUE THREAD

**Issue by markengelhardt** [hlandau/acme#104]
I tried to build acme today:

> yum install go
> git clone https://github.com/hlandau/acme
>  make
> 	[RELOCATE]	  
> 	[GO-GET]	  github.com/hlandau/acme
> \# golang.org/x/crypto/ocsp
> src/golang.org/x/crypto/ocsp/ocsp.go:199: undefined: elliptic.P224
> \# github.com/hlandau/acme/acmeapi/acmeutils
> src/github.com/hlandau/acme/acmeapi/acmeutils/keyauth.go:50: undefined: base64.RawURLEncoding
> \# github.com/hlandau/degoutils/os
> src/github.com/hlandau/degoutils/os/appdata.go:13: undefined: os.LookupEnv
> src/github.com/hlandau/degoutils/os/appdata.go:18: undefined: os.LookupEnv
> src/github.com/hlandau/degoutils/os/appdata.go:23: undefined: os.LookupEnv
> \# gopkg.in/hlandau/service.v2/daemon/caps
> src/gopkg.in/hlandau/service.v2/daemon/caps/caps-linuxc.go:9:28: fatal error: sys/capability.h: No such file or directory
>  \# include \<sys/capability.h\>
>                             ^
> compilation terminated.
> make: *** [.gotten] Error 2

Do I need something else besides "go"

**Comment by hlandau** [comment]
You need Go 1.5.2 or later.

**Comment by markengelhardt** [comment]
Shouldn't the "make" command notify me that I have the wrong version of "go" ?
