### ISSUE TITLE
Access to privkeys is restricted to root 0600 which is not enough for some apps

### ISSUE THREAD

**Issue by bong0** [hlandau/acme#108]
Under debian the access to certificates is usually solved by group-access (dovecot, apache, postfix users etc. are all members of an "ssl-cert" group or something).
Not all applications (like quasselcore) start as root and drop privileges only after having read their cert+privkeys.

It's nice that acmetool watches the permissions but at least group readability should be ensured for the default ssl-group on the specific OS.

I read it up for debian but they have no definitive solution on this :/ https://wiki.debian.org/X.509
reads: 

> The group name ssl-cert is suboptimal because (a) this doesn't necessarily have anything to do with SSL, and (b) it doesn't have to do with certs, that group is created by the ssl-certs package.

So maybe we should just follow common practice there and use the ssl-cert group anyway...

**Comment by hlandau** [comment]
In terms of solving your immediate problem, you can change the configuration for permissions enforcement.
https://github.com/hlandau/acme/blob/master/_doc/perm.example

Something like
```
keys 0640 0750
```
or
```
keys 0640 0750 root some-group
```
should suffice.

**Comment by bong0** [comment]
Yes, indeed! I overlooked this feature. That solves it :) I think that solution is fine as it it. :+1:
