### ISSUE TITLE
RFE: Hook to create just merged key + certificate

### ISSUE THREAD

**Issue by siebenmann** [hlandau/acme#112]
The current `haproxy` hook creates a file that merges key, certificate, and intermediate chain into one file. There is software that wants just a merged key plus certificate, with the certificate chain separately; the case I know is lighttpd (at least it's documented that way). It would be convenient to have a pre-written hook for this, along with a suitable adjustment to the default permissions.

(If this is something of interest, I can take a run at preparing at least preliminary code for it. If so, names for the hook file and the merged file are eagerly accepted, since I'm terrible with names and I'd just call it 'merged' by default.)

**Comment by hlandau** [comment]
I've tested this and lighttpd, thankfully, seems to ignore extra certificates in the PEM file. So you can use haproxy-format files for the privkey and cert, and the chain certs in those files will be ignored. Then configure the `chain` file as the certificate chain file.

**Comment by hlandau** [comment]
I'll add lighttpd to the list of services needing combined files, though.
