### ISSUE TITLE
Quickstart can create an insufficiently customized crontab entry if you use --hooks=/some/dir

### ISSUE THREAD

**Issue by siebenmann** [hlandau/acme#114]
If you specify a custom `--state` setting, `acmetool quickstart` is careful to propagate it into the crontab file it offers to create for you (this is set up in cmd/acmetool/quickstart.go's formulateCron()). However if you also set `--hooks`, such a setting is not also propagated into the crontab.

(If this is considered a real bug, I would be happy to take a go at coding a fix.)

**Comment by hlandau** [comment]
Fix is in master and will be in v0.0.46. Thanks.
