### ISSUE TITLE
Folder proliferation and certificate identification

### ISSUE THREAD

**Issue by tomwaldnz** [hlandau/acme#116]
I currently have two live certificates I've requested using ACME. I've also requested a few testing certificates.

I seem to have a lot of old guff lying around in the desired, certs, and keys folders. Whenever I request a new certificate the number of certs I have seems to change more than I'd expect - I requested one new certificate today and three new folders appeared.

The test certificates seem to stay around as well, so I have a whole load of folders in the certs directory. Also in the desired directory there's many variations of the domains I want - eg "example.com-
zcfn4fr36rdlzkacmyd526vj2" and "example.com-jabc4fr36rdlzkacmyd526vj2".

So my questions are:
1) Should I clear out the old testing certificates, and if so how? Or should I just ignore them?
2) Why are there so many folders with variations of my domain names in the "desired" directory, and should I do anything about it?

**Comment by hlandau** [comment]
The want command shouldn't create a new file in desired if there's already a file in there with the superset of the domains you specified. However, there was a period of time when acmetool didn't do this, so you might have been caught by that. This is harmless. If you have files in desired which specify the same names, you can safely remove all but one of them.

It's safe to delete certificate directories; just run acmetool again afterwards so it can update any symlinks. Ignoring them is also a safe option. acmetool doesn't make any distinction between test and live certificates.

The main thing that concerns me is that you've stated that you're having multiple certificates in the certs directory appear per request. That's not supposed to happen, unless you have old certificates being autorenewed. I suggest you examine these certificates; `openssl x509 -in .../cert -text` will give you information about them. If you care to, you could also try and reproduce this issue using the staging server and with `--xlog.severity=debug 2>&1 | tee debug.log`, which would be helpful to determine if certificates are being requested unnecessarily.

**Comment by hlandau** [comment]
The implementation of the deletion of certificates which have expired and are no longer needed is envisaged. I've created an issue #117 to track implementation of that feature.

**Comment by tomwaldnz** [comment]
I did a thorough clean up of all the directories, the desired directory, certs, keys, everything, then requested certificates for new domains. It's all ok now, so I can't easily reproduce.

You can possibly reproduce by requesting a certificate from prod, then a couple of test ones for different domains, then switching to prod and requesting those.
