### ISSUE TITLE
Requires invalid gopkg.in packages

### ISSUE THREAD

**Issue by gmbuell** [hlandau/acme#119]
Building ACME requires invalid gopkg.in packages:
gopkg.in/hlandau/service.v2/daemon/chroot
gopkg.in/hlandau/service.v2/passwd

Both of those seem to have been moved in v2.0.14

**Comment by hlandau** [comment]
I assume you're using the latest release tag, v0.0.46. Due to a reorganization this will no longer build. I've made a new release, v0.0.47.
