### ISSUE TITLE
OCSP Stapling File Creation

### ISSUE THREAD

**Issue by adam1010** [hlandau/acme#120]
I'm using HaProxy and it's looking for a **domain.pem.ocsp file** in the same directly as the certificate in order to support OCSP Stapling.   Is there a way to have this software generate the OCSP file automatically or with a manual command?  Currently I have to use the "openssl ocsp" command to download the file and save it in the correct location each time I update a certificate.

**Comment by hlandau** [comment]
Ah, more of HAProxy's idiosyncracies. Firstly, of course, use of OCSP stapling is optional. But of course highly desirable.

Firstly, note that manually fetching OCSP isn't going to work; those responses expire after 72 hours, and then things will stop working.

The documentation says:
>For each PEM file, haproxy checks for the presence of file at the same path
suffixed by ".ocsp". If such file is found, support for the TLS Certificate
Status Request extension (also known as "OCSP stapling") is automatically
enabled. **The content of this file is optional. If not empty,** it must contain
a valid OCSP Response in DER format.

I take this to mean that HAProxy can work fine with an empty .ocsp file, presumably to indicate it should staple. You could easily amend the hook script /usr/lib[exec]/acme/hooks/haproxy to touch a `${NAME}.ocsp` file when it creates the haproxy directory.

**Comment by adam1010** [comment]
I tried using an empty .ocsp file but HaProxy 1.6 wouldn't accept it so it appears that it will not fetch the contents on-demand. It appears that a cron job approach is the way to go. If it's out of scope to have a command for downloading the .ocsp file (which can be called from a cron job), then go ahead and close this issue. I thought it might save others the pain of using 3rd-party scripts to obtain the newest OCSP file every couple days  (but I do see the issue if people forget to setup the cron job and then have stale .ocsp files hanging around)

**Comment by hlandau** [comment]
I think the absurdity of HAProxy in this regard is out of scope for acmetool. If people are using HAProxy, one can only assume they're aware of, and willing to deal with, its idiosyncracies. Since there appears to be an adequate ecosystem of separate tools to create OCSP files for HAProxy, I'm closing this.
