### ISSUE TITLE
Strange error messages when requesting a cert signing

### ISSUE THREAD

**Issue by simonszu** [hlandau/acme#126]
Hi,
i have noticed the following: 
When i execute a `want` or `reconcile` process, i get lots of error messages, and i can't explain why. 

***
Please notice that i have changed the challenge response webroot to `/var/lib/acme/challenges`, instead of the default `/var/run` path. So there is an error in the certificate creation process:
```
20160216095423 [ERROR] acme.responder: failed to open webroot file /var/run/acme/acme-challenge/VduVzwGAtEuDzWmNKwsB3Efw9pybaX-kIfj0HlUF0jc: open /var/run/acme/acme-challenge/VduVzwGAtEuDzWmNKwsB3Efw9pybaX-kIfj0HlUF0jc: no such file or directory
```
Nevertheless, there is the specified challenge file created in `/var/lib/acme/challenges`, the challenge response fails, and the challenge file isn't deleted afterwards. There does indeed appear a certificate in `/var/lib/acme/live`, but it isn't signed by LE. Why is the responder still pointing at `/var/run`? I have to mention that the webroot-paths in `/var/lib/acme/conf/target` is also pointing to the `/var/lib` path. 
***
The second error message is regarding the hooks. I have set up acmetool as rootless setup, and the following line in my sudoers conf: `acme ALL=(root) NOPASSWD: /usr/lib/acme/hooks`. The hooks directory is properly set with the setuid flag, and owned by root. But i get these errors when i execute a want:
```
20160216100710 [ERROR] acme.hooks: hook script: /usr/lib/acme/hooks/haproxy: exit status 1
sudo: Password needed
20160216100710 [ERROR] acme.hooks: hook script: /usr/lib/acme/hooks/reload: exit status 1
sudo: Password needed
``` 
I have noticed that these errors only happen when i set the setuid bit, not, if i remove this bit. 
***

So, if someone has an idea why the webroot seems to be hardcoded somewhere, and why i cannot set the setuid bit (like in the installation manual) without spawning a lot of errors, and without knowing if the hooks execution succeeds, please tell me.

**Comment by simonszu** [comment]
Ah, my fault. I have figured out the first issue. I didn't know about the Challenge Completion Philosophy, and the unsigned Certs were accidentally run against the testing server. 
However, i still don't know how to handle the hooks properly.

**Comment by hlandau** [comment]
2. Setting setuid on a script (i.e. something with a shebang line, so something UNIX can't normally execute setuid) is an indication to acmetool that it should execute it by running `sudo -n -- /path/to/hook ...`. So you might want to try running `sudo -n -- /path/to/hook ...` as the acme user and see what happens.

**Comment by hlandau** [comment]
If the challenge files aren't being deleted afterwards, that is actually a bug -- hmm. Also, I should probably convert that error into an info-level message, since if you're running acmetool from cron and have cron set up to mail you log output (and you should), it's going to annoy you whenever it renews. Workarounds: Use --xlog.severity=critical in cron, or just redirect all stderr output to /dev/null: `2>/dev/null`. (acmetool will exit with an error return code, so cron should still notify you if it fails.)

**Comment by simonszu** [comment]
So i executed `sudo -n -- /path/to/hook ... ` as the acme user (without setuid) and got the error that a password is needed. 
I changed the setuid bit to enabled after that, and still got the same error. 

Yes, a suppressing these error messages would be nice. Each error message spawned a new mail on its own, and each certificate spawned around 6 to 8 errors (because of the hooks permissions). I currently have 12 subdomains on this host, each with its own certificate, since LE doesn't support wildcard certificates, so today in the morning i got 96 mails from cron that there was something wrong, 
and now my own mailserver running on the same host had had itself in spam protection, because 98 mails with similar content is quite spammy :D

**Comment by hlandau** [comment]
The setuid bit won't make any difference to sudo or to the kernel; acmetool just uses it as a flag. I'm not aware of any other software that cares about the setuid bit on a shell script.

So you have some sort of configuration issue with sudo.
I think you need to name the challenge files explicitly:

```
acme ALL=(root) NOPASSWD: /usr/lib/acme/hooks/reload
```

**Comment by hlandau** [comment]
Changed logging level for that error to info, will be in next release.

**Comment by simonszu** [comment]
> I think you need to name the challenge files explicitly
Yes, this seem to work. Thank you.
