### ISSUE TITLE
quickstart fails when cron isn't installed

### ISSUE THREAD

**Issue by kpcyrd** [hlandau/acme#127]
I've started `acmetool quickstart` and chose to install the cronjob. Turned out cron wasn't installed because the system was debootstrapped, so /etc/cron.d didn't exist yet.

This causes the following error:

```
20160215121110 [ERROR] acmetool: failed to install cron job at /etc/cron.d/acmetool (does the file already exist?), wanted to install: SHELL=/bin/sh
[...]
```

**Comment by hlandau** [comment]
Hmm, this is odd.

If you look at quickstart.go:351, if /etc/cron.d doesn't exist, and you're running acmetool as root it issues a warning. But then it asks anyway. I think I forgot to put in 'return' after the Warnf call. So I'll do that.

**Comment by hlandau** [comment]
Whoops, forgot to close this. This is fixed.
