### ISSUE TITLE
Need a better way to determine zone apex in nsupdate DNS hook

### ISSUE THREAD

**Issue by sopium** [hlandau/acme#130]
Say `a.example.com` has CNAME `a.something.else`, then the hook script (sometimes?) uses ns servers of `a.something.else` in `waitns()`, and waits forever...

Well I don't really understand DNS, but shouldn't the script still use ns servers of `example.com`?

**Comment by hlandau** [comment]
If you change `get_apex "$CH_HOSTNAME"` to `get_apex "_acme-challenge.$CH_HOSTNAME"`, does this fix the problem?

**Comment by sopium** [comment]
That does not seem like an appropriate fix. `dig +noall +answer SOA "_acme-challenge.$CH_HOSTNAME"` would not have answers, and we are back to `get_apex $CH_HOSTNAME`.

I would suggest checking whether `APEX` is a suffix of `CH_HOSTNAME`, in `get_apex()`.

But I actually cannot reproduce the problem anymore... Close if you'd like to.

**Comment by sopium** [comment]
> I would suggest checking whether APEX is a suffix of CH_HOSTNAME, in get_apex().

No that's not a fix either. And I was able to reproduce it again:

> $ dig +noall +answer SOA [xxx.xxxxxx.xxx]
[xxx.xxxxx.xxx]	129	IN	CNAME	vt-cn3.vnet.link.
vt-cn3.vnet.link.	447	IN	SOA	ns-soa.vnet.link. ns-admin.vnet.link. 1 1800 3600 604800 3600

Better come up with a better way to determine apex?
