### ISSUE TITLE
acme-dns-hook-cloudflare: please test, comment...

### ISSUE THREAD

**Issue by yinguanhao** [hlandau/acme#131]
I have created [acme-dns-hook-cloudflare](https://github.com/yinguanhao/acme-dns-hook-cloudflare), a DNS challenge hook using cloudflare API.

Please test, comment and perhaps include it or mention it in you docs.

**Comment by hlandau** [comment]
I don't use cloudflare but I've added your script to the documentation. Thanks.

https://hlandau.github.io/acme/userguide#annex-external-resources-and-third-party-extentions
