### ISSUE TITLE
Add a --force option for "want"

### ISSUE THREAD

**Issue by thomaskonrad** [hlandau/acme#137]
Hi,

by default, if the current certificate is still valid, ```acmetool``` skips the target and does not request a new certificate. But in order to test the reconciliation mechanism, it would be great to have a ```--force``` option so that ```acmetool``` requests a new certificate in any case.

Thanks
Thomas

**Comment by petercolberg** [comment]
Initially I had been missing this feature as well when testing acmetool using the staging server. Then I found that revoking an existing valid certificate triggers a request for a new certificate to satisfy the requirements, which is quite useful for repeated testing.

**Comment by hlandau** [comment]
Indeed - you can solve this via revocation. Adding a `--force` option to want doesn't make sense given the architecture of acmetool. Closing this.
