### ISSUE TITLE
hooks do not work on debian 8

### ISSUE THREAD

**Issue by apollo13** [hlandau/acme#138]
So Debian 8 does have systemctl, but no service files for quite a few services (apache2 beeing a good example). Now as soon as systemctl exists, it tries to reload using systemctl assuming apache2.service exists, which it does not. Sadly add the end of the hooks there is an exit 0 preventing service from beeing used. Is there any harm in dropping the systemctl part? service exists on pretty much every platform…

**Comment by hlandau** [comment]
Perhaps I should move the `service` block above `systemctl`.

**Comment by apollo13** [comment]
That would work too, yes

**Comment by hlandau** [comment]
Actually, this already seems to be the case. I think I already made this change some time ago. Are you using an older version?

https://github.com/hlandau/acme/blob/master/cmd/acmetool/quickstart.go#L125

**Comment by apollo13** [comment]
Oh, yes. Sorry. That said, would a new version of acmetool override an existing hooks script?

**Comment by hlandau** [comment]
Only if a) you run quickstart again and b) the script contains the string `#!acmetool-managed!#` near the start of the file.
