### ISSUE TITLE
Switch to upstream gopkg.in/cheggaaa/pb.v1

### ISSUE THREAD

**Issue by petercolberg** [hlandau/acme#139]
The forked package github.com/hlandauf/pb contains one additional commit over the upstream package github.com/cheggaaa/pb that fixes compilation on Dragonfly BSD. Could you file a pull request for commit hlandauf/pb@0c1cdef, and then substitute `github.com/hlandauf/pb` → `gopkg.in/cheggaaa/pb.v1`?

The upstream author has recently added semantic versioning cheggaaa/pb#73.

**Comment by hlandau** [comment]
Switched to `gopkg.in/cheggaaa/pb.v1`.
