### ISSUE TITLE
Allow file permissions to be set by hostname

### ISSUE THREAD

**Issue by maufl** [hlandau/acme#140]
I would like to set the permissions for a single domain.
In conf/perm I tried:

        live/xmpp.maufl.de/*   0640 0750 root prosody

But this does nothing.
How am I supposed to apply permissions to live folders?

**Comment by hlandau** [comment]
The permissions file is recursive. What you are trying will not work because the live directory contains only symlinks. You need to change the permissions on the certs and keys directories. There isn't really any way to restrict this to certificates bearing particular hostnames.

**Comment by maufl** [comment]
Ok. I think what I meant was, set permissions and follow symlinks. Obviously it would conflict with permission requirements for other folders.
But I think it would be desirable to be able to set permissions by particular hostnames.

**Comment by hlandau** [comment]
One possible workaround for this would be to use a hook script to copy certificates and keys to another location and set their permissions as you like.

This feature is unlikely to be implemented for the foreseeable future.

**Comment by maufl** [comment]
OK, thank you. This issue can probably be closed then.

**Comment by CyBeRoni** [comment]
> There isn't really any way to restrict this to certificates bearing particular hostnames.

This is kind of necessary though, as the keys are rotated every so often. So if I need, for example, slapd and exim to have access to a private key (which they access under their own uid, not root), then I could enter in the perm file:

``
keys/auzo2rnl7tgvgl23dj4trz6b6dehysxuulq7ynketkne6spgzm7a 0640 0751 root Debian-exim
keys/bbfbzhavir6il5meksgbsxzdwplrcqlk52w6zk3hxjjxsjgyjynq 0640 0750 root openldap
``

And it would work but break a few months down the line when the key is rotated.

So perhaps this issue could be re-considered?

**Comment by hlandau** [comment]
@CyBeRoni There's no way to set different permissions for some keys than others, and since keys, certificates and hostnames aren't directly correlated to one another, this is unlikely to be implemented.

Your options are:

- Create an additional group (`privkey` or somesuch) and add all users which need access to keys to it, and then use a permission file to configure all keys to that group and mode 640.
- Use a notify script to copy the desired keys to somewhere else with the desired permissions after acmetool runs. This is the most flexible option.

**Comment by CyBeRoni** [comment]
>  There's no way to set different permissions for some keys than others

Of course there is. You could resolve the privkey symlink and update the permissions of the referenced file instead.

> Create an additional group (privkey or somesuch) and add all users which need access to keys to it,

This gives all my services access to all my private keys and is as such problematic in terms of security.

> Use a notify script to copy the desired keys to somewhere else with the desired permissions after acmetool runs. This is the most flexible option.

It's also the least maintainable.
