### ISSUE TITLE
Provide ARM builds in PPA

### ISSUE THREAD

**Issue by dakky** [hlandau/acme#141]
Greetings.

I want to run acmetool on an raspberry pi which has an ARM arch. Are there any deb repos to use?
`Linux hostname  4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux`

**Comment by hlandau** [comment]
Currently the PPA, which also works with Debian, isn't set to build for armel. I should change this.

**Comment by hlandau** [comment]
Now available in PPA.
