### ISSUE TITLE
try another auth mechanism after failing

### ISSUE THREAD

**Issue by dakky** [hlandau/acme#146]
the scenario: empty host with full configuration management

- installing acmetool and running firstrun with proxy as auth mechanism => fails, because httpd/nginx/whatever is not yet present
- installing httpd/nginx/whatever first will fail, because there a no certs available => daemon crash
- installating apache and requesting certs with redirector mechanism => fails, because port 80 is blocked

A nice solution would be to setup  acmetool the following way:
try mechanism A, if it fails mechanism B

so in my case:
acmetool configured to use proxy first, redirector on failure.
if initial setup or existing webserver is broken/down/whatever => proxy will fail, redirector will (probably :D succeed)
if everthing is fine and its an regular update interval: proxy will succeed

**Comment by hlandau** [comment]
acmetool already does this.

**Comment by dakky** [comment]
hmm srsly? has this to be configured somewhere? when selecting "proxy" in quicksetup and trying to get certs without a running and configured (upstream to port 402) nginx, requesting certs failed.

**Comment by hlandau** [comment]
No configuration is required.
