### ISSUE TITLE
acmetool want - allow to specify the primary name

### ISSUE THREAD

**Issue by cboltz** [hlandau/acme#149]
If I request a certificate with
 `    acmetool want example.com www.example.com old-compat-domain.example.com`
it seems to be random which domain name is used as primary domain (as displayed in a browser's certificate info) and which are specified as SAN.

It would be nice if I could specify which of the names should be the primary one.

(CC @ccboltz)

**Comment by hlandau** [comment]
What version of acmetool are you using? I believe this was fixed.

**Comment by cboltz** [comment]
acmetool-0.0.49-1.fc23.x86_64 (the Fedora RPM, even if I'm running openSUSE Leap ;-)

**Comment by hlandau** [comment]
This was fixed in 0.0.50. https://github.com/hlandau/acme/releases/tag/v0.0.50
