### ISSUE TITLE
document error behavior

### ISSUE THREAD

**Issue by joeyh** [hlandau/acme#15]
Reading the documentation it's not clear what happens if a requested certificate cannot be obtained, or if a certificate renewal cannot be prerformed in time. I'd hope for reasonable error messages and nonzero exit status of the command. Documenting this is important to allow for planning for these exceptional circumstances that can't easily be tested.

**Comment by joeyh** [comment]
Also, if cert renewal is failing for some reason, there should be an indication of it well before the certificate expires, so there's eg 1 month for the admin to fix the problem. That time period should probably be configurable.

**Comment by hlandau** [comment]
acmetool will start trying to obtain a new certificate 30 days before expiry, or 66% of the way through the validity period, whichever is lower. I'll improve the documentation.

**Comment by hlandau** [comment]
Documentation fixed.
