### ISSUE TITLE
lighttpd generally needs a restart, not a reload, to pick up a new certificate

### ISSUE THREAD

**Issue by siebenmann** [hlandau/acme#152]
The current 'reload' hook script uses various forms of 'reload' to reload daemons in order to pick up new certificates. As I discovered yesterday when my certificates renewed for the first time, lighttpd (at least on Fedora 23) doesn't actually support a 'reload' operation; you must restart the daemon instead. Attempts to reload the service get an error:

    # service lighttpd reload
    Redirecting to /bin/systemctl reload lighttpd.service
    Failed to reload lighttpd.service: Job type reload is not applicable for unit lighttpd.service.

Unfortunately the script doesn't recognize this situation because it discards the error from reload attempts.

I'm not sure of the best solution for this. One option would be a new 'restart' hook script, but it's surprisingly hard to write something that works generally but only restarts daemons if they're actually running (as not everything necessarily supports the `condrestart` option); you might have to require users to explicitly configure what daemons to act on. Another would be to change the 'reload' hook so that systemctl is the first method tried and then change it from doing `systemctl reload ...` to doing `systemctl reload-or-try-restart ...`, which automatically restarts the service if it doesn't support reload (and it's running). This would automatically fix systemd systems, although it leaves other ones sort of out in the cold.

**Comment by Thermi** [comment]
That's not true. lighttpd can be restarted with SIGHUP.  http://blog.lighttpd.net/articles/2007/09/02/there-is-an-angel-for-lighty/ Just add a corresponding `ExecReload` line in the unit. Looks like that. 
`ExecReload=/bin/kill -HUP $MAINPID`

**Comment by hlandau** [comment]
Assuming this is resolved.
