### ISSUE TITLE
wrong intermediate certificate in chain / fullchain files?

### ISSUE THREAD

**Issue by haraldkoch** [hlandau/acme#154]
I just imported a group of certificates from the lets encrypt client using `acmetool import-le`. For some reason I then had to run `acmetool want ....` for each domain - which surprised me, and may be related to my issue.

So now, the certificates in `live/domain/cert` are the old certificates from the letsencrypt environment, issued by the Let's Encrypt X1 root, but the intermediate cert in the `chain` and `fullchain` files are the new Let's Encrypt X3 root.

Example:

```
% pwd
/var/lib/acme/live/hilladr.com
% openssl x509 -in cert -noout -subject -issuer
subject= /CN=www.hilladr.com
issuer= /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X1
% openssl x509 -in chain -noout -subject
subject= /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3

```

Thoughts?

**Comment by hlandau** [comment]
It's correct to have to run `want`. Importing certificates doesn't create a target.

This is a bug in the Let's Encrypt service, not acmetool. Let's Encrypt switched to serving the X3 intermediate at its ACME server, but does so even for certificates which were originally issued under X1. The only available workaround is to manually edit the files to contain the correct intermediate.

**Comment by haraldkoch** [comment]
Excellent - I shall clean up my environment. Thanks for the quick response.
