### ISSUE TITLE
acme.responder: http-01 self test assumes HTTP rather than HTTPS

### ISSUE THREAD

**Issue by rsesek** [hlandau/acme#155]
The acme.responder http-01 self test assumes that sites actually serve traffic on HTTP, not just HTTPS.

My site has always been configured for HTTPS and so HTTP traffic is not even set up. In Apache I had this configuration:

```
<VirtualHost *:80>
        ServerName example.com

        RewriteEngine on
        RewriteCond %{HTTPS} off
        RewriteRule / https://example.com/
</VirtualHost>
```

When setting up a webroot challenge responder, I noticed that the self test was failing:

20160410173509 [DEBUG] acme.hooks: calling hook script (with sudo): /usr/libexec/acme/hooks/reload
20160410173509 [DEBUG] acme.responder: http-01 self test
20160410173509 [INFO] acme.responder: http-01 self test failed: got 200 response when doing self-test, but with the wrong data

Self test does the right thing and follows the redirect, but because of the configuration, http://example.com/.well-known/acme-challenge/X will get redirected to the bare https://example.com, rather than a deep-link into the HTTPS site. I investigated and found that the self test assumes a HTTP scheme (https://github.com/hlandau/acme/blob/66ffc6fa9081bae92e33cd3fde652d0126e914b9/responder/http.go#L112), so I had to modify my configuration like so:

```
<VirtualHost *:80>
        ServerName example.com

        RewriteEngine on
        RewriteCond %{HTTPS} off
        RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/
        RewriteRule / https://example.com/

        DocumentRoot /home/httpd/site/html
</VirtualHost>
```

Self test could improve this flow by trying a https scheme if the http scheme fails.

**Comment by haraldkoch** [comment]
As a workaround, you could also use something like

`RewriteRule ^(.*)        https://%{SERVER_NAME}$1     [R,L]`

Which is a fairly standard deep-linking redirect. This will also make happy users who type URLs forgetting the HTTPS.

(The [R,L] is paranoia on my part, since apache is supposed to do exactly that when given a full URL..)

**Comment by rsesek** [comment]
According to Apache, the recommended practice is to not redirect to a deep-link, but only to the homepage https://httpd.apache.org/docs/current/rewrite/avoid.html#redirect. So the desired config really should just be:

```
<VirtualHost *:80>
        ServerName example.com
        Redirect / https://example.com/
</VirtualHost>
```
It's best not to rely on HTTP -> S redirects anyways, but instead set HSTS (which I also do). http://blog.michaelhidalgo.info/2013/09/redirecting-http-traffic-to-https-why.html

**Comment by haraldkoch** [comment]
Yes! Redirect is much better and I need more coffee.

**Comment by hlandau** [comment]
I'm not sure I follow. The ACME protocol requires that challenge files be retrieved from an `http://` URL, not an HTTPS one. The protocol does allow a redirect to be returned to a request of the form `http://example.com/.well-known/acme-challenge/xyz`, even as I understand it to an HTTPS URL or a different domain, but obviously you would need to ensure it redirects to the right URL.

**Comment by rsesek** [comment]
Ah, I didn't realize that the protocol required HTTP challenge responses. An older version of the spec (https://letsencrypt.github.io/acme-spec/#rfc.section.7.1) did permit HTTPS response challenges, but the latest working draft (https://tools.ietf.org/html/draft-ietf-acme-acme-02#section-7.2) does not.

Maybe the only thing that can be improved then is printing the initial request URL and final response URL. Otherwise, I think this has to be closed per the spec.
