### ISSUE TITLE
DoS vuln in OCSP checking

### ISSUE THREAD

**Issue by takeyourhatoff** [hlandau/acme#157]
https://github.com/hlandau/acme/blob/master/acmeapi/ocsp.go#L52

https://github.com/xenolf/lego/issues/56

**Comment by hlandau** [comment]
Thanks.

**Comment by petercolberg** [comment]
Does this vulnerability not also apply to other occurrences of `ioutil.ReadAll(res.Body)`?

**Comment by takeyourhatoff** [comment]
https://github.com/hlandau/acme/blob/master/acmeapi/api.go#L538
Yes.
I didn't go and find every violation, but I'll quote myself from the issue I raised in lego:

> Remember that ioutil.ReadAll is not safe to call when you do not know the length of the io.Reader.
