### ISSUE TITLE
How to perform a stateless challenge

### ISSUE THREAD

**Issue by chosenken** [hlandau/acme#158]
Hi, I can't find any documentation anywhere on how to perform a stateless challenge.  I understand that I need the account key registered with let's encrypt, but I don't know how to create the response for the challenge.

I want to be able to request certs for multiple subdomains programmatically using the same account key, and I need to be able to create the challenge response.

I see from the let's encrypt official tool, if you do it for `certonly` and manually, it creates a file with the challenge token containing `{TOKEN}.{DATA}`.  I'm trying to figure out how to produce the `{DATA}` text in the challenge file.

**Comment by hlandau** [comment]
An example configuration for nginx is shown here. https://hlandau.github.io/acme/userguide#web-server-configuration-challenges
