### ISSUE TITLE
Allow for responses to be automatically provided to prompts

### ISSUE THREAD

**Issue by joeyh** [hlandau/acme#16]
acmetool want foo popped up a dialog with 2 lines asking if I accepted the letsencrypt service agreement, and 39 lines of empty space. The remainer of the dialog was too large to display in my 80x40 terminal window, which made it unusable.

The quickstart has the same problem with assuming large screen size.

Personally, I don't want these dialogs at all; I want to be able to completely script use of it from the command line.

**Comment by hlandau** [comment]
A `--stdio` option to force use of stdio prompts rather than dialogs will be added in v0.0.13, which I will release today.

But maybe acmetool should have ways of prespecifying responses to prompts as well?

**Comment by asquelt** [comment]
:+1:  that would make it easier to set it up with CM tools (puppet, chef, ansible, ...).

**Comment by hlandau** [comment]
The interaction system is already internally designed around this; each dialog has a unique ID. This is actually used to auto-respond to the quickstart messages when running tests. So I should expose this publically. Maybe something like

```
acmetool quickstart --respond acme-agreement:https://letsencrypt.org/some-agreement-url=1
```

or maybe a file

```
# acmetool quickstart --response-file foo
# cat foo
"acme-agreement:https://letsencrypt.org/some-agreement-url": 1
```

See `cmd/acmetool/main_test.go` for some of the prompt IDs currently supported.

**Comment by hlandau** [comment]
A response file can now be specified. See the `--response-file` argument and the example file in _doc. v0.0.15.

**Comment by simonszu** [comment]
You should add `"acmetool-quickstart-webroot-path-unlikely": true` to the response-file template in _doc to automate the answer to the question if your webroot is valid despite it not ending in .acme-challenge.

**Comment by hlandau** [comment]
I've changed it so that acmetool-quickstart-webroot-path-unlikely a) doesn't show in batch mode and b) doesn't show if the webroot path came from a response file. Also failures to show the prompt will result in continuing. Will be in v0.0.39.
