### ISSUE TITLE
haproxy detection fails on ubuntu 14.04.4

### ISSUE THREAD

**Issue by felx** [hlandau/acme#165]
I think detection fails because the access rights of my haproxy installation were set to 777
When forcing haproxy detection using HAPROXY_ALWAYS_GENERATE, acmetool complains about bad permission on /usr/local/sbin/haproxy then change it to 666

**Comment by hlandau** [comment]
acmetool doesn't do any permissions verification on executables. The only place it verifies permissions is on its state directory.
