### ISSUE TITLE
[acme.solver] "waiting to poll challenge" gives up to fast

### ISSUE THREAD

**Issue by dol** [hlandau/acme#167]
I implemented a challenge-dns-start hook. The hook script creates a new DNS record. When I tested acmetools with my hook the challenge was never completed. I had to add some seconds of sleep time to my hook script because the acme.solver gives up to fast.
https://github.com/hlandau/acme/blob/a7e73d378ea3a85a8ed35909b10747682c5f0b47/solver/respond.go#L157 notes, that the resolver tries for 30 seconds. This is IMHO to quick for a DNS challenge. Some nameserver aggregate the DNS changes and push them to the edge nodes in batches. An upper limit if 600 seconds might better.

**Comment by hlandau** [comment]
This isn't how it works. The ACME server will attempt to verify the challenge once, and failure to verify the challenge that one time will result in permanent failure of that challenge attempt. As such, it is essential that the hook script only exit once the record is globally visible at all nameservers. This is the responsibility of the hook script. See the [specification](https://github.com/hlandau/acme/blob/master/_doc/SCHEMA.md#challenge-dns-start-challenge-dns-stop) and the [example script](https://github.com/hlandau/acme/blob/master/_doc/dns.hook#L47).

**Comment by dol** [comment]
@hlandau Sorry, I had in mind that a challenge verification could be triggered multiple times. You're right.
