### ISSUE TITLE
Support for --expand?

### ISSUE THREAD

**Issue by c17r** [hlandau/acme#169]
Say you have a cert already that covers

* example.com
* www.example.com
* sub1.example.com

Now you want to add `sub2.example.com` to the same cert.  The official client has `--expand` which says
```
--expand              If an existing cert covers some subset of the
                      requested names, always expand and replace it with the
                      additional names. (default: False)
```

unless I'm missing something the only way to handle it in acmetool is to `unwant` the original and then `want` all the old ones names with the new one?

**Comment by hlandau** [comment]
You can't change certificates. Any change requires a new issuance.

When adding a name to a list of names required to appear on the same certificate, this creates a set of names which is a superset of the old set of names. Thus, both the old target and new target will be satisifed by a certificate satisfying the new target. So you can just run first
```acmetool want example.com www.example.com sub1.example.com`
and then later, when you want to add `sub2.example.com`
```acmetool want example.com www.example.com sub1.example.com sub2.example.com```.
This will result in a new certificate being created, and it will satisfy both targets, so in the future (during autorenewal, etc.) only one certificate will be created.

If you like you can delete the old target file, but it's inconsequential and won't result in additional issuances. Don't use 'unwant' for this as it removes the names mentioned from all target files found.

**Comment by ulope** [comment]
The problem with this is that now you will get confusing emails from LetsEncrypt warning you about expiring certs that in reality are only a subset of the "real" new certificate.

**Comment by mnalis** [comment]
That is the problem with let's encrypt servers themselves, not with a acmetool. LE doesn't ever let you "update" certificates, it can only issue new ones.

You can work around that by unsubscribing from lets encrypt emails for that host with multiple domains, and use your icinga/nagios or external monitors like https://letsmonitor.org/ to warn you in case there are problems with certificate
