### ISSUE TITLE
haproxy state dir is created world-writable

### ISSUE THREAD

**Issue by hansmi** [hlandau/acme#171]
The `/var/lib/acme/haproxy` directory by the haproxy hook is created with a umask of `0000`, leading to a world-writable directory.

Before running an initial `reconcile`:
```
# ls -lhd /var/lib/acme/haproxy
ls: cannot access /var/lib/acme/haproxy: No such file or directory
```

Afterwards:
```
# ls -lhd /var/lib/acme/haproxy
drwxrwxrwx 2 acme acme 4.0K Jun 21 10:57 /var/lib/acme/haproxy
```

While others may not be able to read certificates and keys, they can at least create some havoc:

```
# sudo -u nobody rm -fv /var/lib/acme/haproxy/domain.tld
removed '/var/lib/acme/haproxy/domain.tld'
```

I verified the umask being `0000` by inserting `umask > /tmp/…` into `/etc/default/acme-reload`. Explicitly setting the umask in the same script works around the issue (e.g. `umask 0077`).

**Comment by hlandau** [comment]
Can you confirm that this is corrected when acmetool is next run?
```
[WARN] fdb: "haproxy" has wrong mode -rwxrwxrwx, changing to -rwxr-xr-x
```

Still needs to be fixed, of course. On it.

**Comment by hansmi** [comment]
Yes, I can confirm that it's corrected on the next run.
