### ISSUE TITLE
acmetool removes read access to group for private keys

### ISSUE THREAD

**Issue by fauno** [hlandau/acme#173]
To give different services read access to the private keys I'm using a group, like so:

```bash
chmod -R g=srX /var/lib/acme/keys
chgrp -R ssl-cert /var/lib/acme/keys
gpasswd -a prosody ssl-cert
```

But when I run `acmetool`, it enforces read access only to the acme user, which is not very useful.  Is there a reason for this?

**Comment by hlandau** [comment]
You can override this with a permissions file:

https://github.com/hlandau/acme/blob/master/_doc/perm.example
