### ISSUE TITLE
Possibility to use specific Authorization type and specifying hook/hooks to use

### ISSUE THREAD

**Issue by md2k** [hlandau/acme#174]
Hi all, i noticed that acmetool trying to authorize using all available methods and do not allow to set which method exactly i want to use. I found that a bit strange because:
If i want to use DNS Auth, then i should ensure that my ports 80/443 is busy with some application, and acmetool not able to get them, otherwise HTTP auth will be in use
This is broke automation in my opinion, i have single server which used for Certificates generation, which not have any web applications and acmetool always binding itself on port 80, of course, since domain not pointing to this server, auth failed and it go further to other types of Auth. But why need at all try all types if we know that we want to use DNS challenge only?
Regarding hooks, from your documentation i not found any possibility to use specific hook for specific domain(s), this is rise another concern:
I have some amount of domains, part of them with CloudFlare , part with AWS Route53, since DNS hook can be only one, there is no any easy way to handle more then 1 DNS provider to work with.

Maybe i missed something in documentation, so any input will be valuable for me.

**Comment by hlandau** [comment]
As part of the challenge completion philosophy, acmetool will always try all methods to complete challenges. If a method fails, this is inconsequential.

https://hlandau.github.io/acme/userguide#challenge-completion-philosophy

acmetool doesn't support applying hooks to only some domains. As a workaround, you could make a DNS hook conditional by incorporating a list of supported domains into the script itself.

**Comment by md2k** [comment]
Got it, thanks.
