### ISSUE TITLE
interaction/dialog.go crashes if whiptail does not understand --yes-button

### ISSUE THREAD

**Issue by kkofler** [hlandau/acme#18]
CentOS 5 ships an old `whiptail` that does not understand `--yes-button`. This makes `interaction/dialog.go` crash when it prompts for accepting the license. As a result, I cannot go beyond the registration step. Workaround: `sed -i -e s/whiptail/whipt4il/g acmetool`, which makes it fall back to plain stdio (because there is no `whipt4il` binary).

I tried to install `dialog`, but that is also either too old or otherwise not compatible, because there, I get a complaint about `--no-tags` not being supported (but in that case, it at least seems to fall back to stdio just fine; I didn't try going through the process that way though, but simply uninstalled `dialog` which I had installed just for `acmetool`).

After working around both issue #17 and this issue, `acmetool` 0.12.0 runs on CentOS 5.

**Comment by hlandau** [comment]
So I guess I need to either fallback to stdio when whiptail/dialog fails, or do a version check on them. Annoyingly whiptail exits with exit code 1 when passed an unsupported option, which is the same code used when a user selects No.

I'll disable whiptail for now and treat 255 error codes from dialog as meaning fallback to stdio should be done. I'll also add a `--stdio` flag to force use of basic prompts.

**Comment by hlandau** [comment]
v0.0.13 is now available, which disables whiptail, falls back to stdio if dialog fails, and provides `--stdio`.

**Comment by kkofler** [comment]
For the record, the machine has `whiptail (newt): 0.52.1`, which supports the following command-line options:
```
Box options: 
        --msgbox <text> <height> <width>
        --yesno  <text> <height> <width>
        --infobox <text> <height> <width>
        --inputbox <text> <height> <width> [init] 
        --passwordbox <text> <height> <width> [init] 
        --textbox <file> <height> <width>
        --menu <text> <height> <width> <listheight> [tag item] ...
        --checklist <text> <height> <width> <listheight> [tag item status]...
        --radiolist <text> <height> <width> <listheight> [tag item status]...
        --gauge <text> <height> <width> <percent>
Options: (depend on box-option)
        --clear                         clear screen on exit
        --defaultno                     default no button
        --default-item <string>         set default string
        --fb                            use full buttons
        --nocancel                      no cancel button
        --noitem                        display tags only
        --separate-output               output one line at a time
        --output-fd <fd>                output to fd, not stdout
        --title <title>                 display title
        --backtitle <backtitle>         display backtitle
        --scrolltext                    force vertical scrollbars
```
