### ISSUE TITLE
acmetool deletes unrelated broken symlinks

### ISSUE THREAD

**Issue by cboltz** [hlandau/acme#180]
```
# /usr/bin/acmetool --batch reconcile
20160718224301 [WARN] fdb: broken symlink, removing: /var/lib/acme/.local/share/systemd/user -> ../../../.config/systemd/user
```

Why does acmetool look into /var/lib/acme/.local/ and delete a (broken) symlink from it? It has nothing to do with certificates...

In case it matters: I'm using the acmetool-0.0.50-1.fc23.x86_64 RPM package.

(mail copy to @ccboltz)

**Comment by hlandau** [comment]
This is correct. acmetool excercises dominion over its certificate directory and may remove anything inconsistent it finds in there. The purpose of the state directory is to conform with the [specification](https://github.com/hlandau/acme/blob/master/_doc/SCHEMA.md), and acmetool will remove broken symlinks and change permissions recursively as it thinks proper.

Don't set the state directory to something general, or a directory used for any other purpose.

**Comment by petercolberg** [comment]
> Hmm, sounds like it's a bad idea to use /var/lib/acme/ as the home directory of the "acme" user

This should work fine, using `sudo -u acme acmetool` for interactive execution when needed. Is there a reason why you created user-specific systemd configuration, instead of placing it in the system-wide directory `/etc/systemd/system`?

**Comment by cboltz** [comment]
I didn't create any systemd-specific configuration in /var/lib/acme.

I noticed the message while the daily reconcile cronjob was running (as user acme).

My guess is that systemd creates that symlink while running the reconcile cronjob (which means starting a user session for the acme user, run acmetool reconcile and close that user session again).
