### ISSUE TITLE
CheckOCSP does not return OCSPStaple

### ISSUE THREAD

**Issue by nhooyr** [hlandau/acme#182]
CheckOCSP does not return the the actual byte response from the server so it cannot be used for ocsp stapling.

See how lego does it [here](https://github.com/xenolf/lego/blob/b12ce5e73146e74520c426895394b92dffeb3a25/acme/crypto.go#L56)

It returns both the byte response and the parsed OCSP response.

btw is there any reason acmeapi prefers to use http get over post to request the OCSP response? (I dont know which is better, just wondering if there is any thought behind the decision)

**Comment by hlandau** [comment]
GET is probably preferred for retrieving OCSP responses nowadays since it makes it easier for CDNs to cache them like any other HTTP request.

Looking into this.

**Comment by hlandau** [comment]
Added CheckOCSPRaw method.
