### ISSUE TITLE
a dep depends on the now missing launchpad.net/mgo/bson

### ISSUE THREAD

**Issue by jmhodges** [hlandau/acme#183]
Tried to vendor github.com/hlandau/acme/acmeapi into a repo and my vendoring tool pointed out that launchpad.net/mgo/bson doesn't seem to exist anymore.

hlandau/acme depends on that through the chain of repos: 

    github.com/hlandau/acme/acmeapi
    github.com/hlandau/degoutils/net
    gopkg.in/vmihailenco/msgpack.v2
    github.com/ugorji/go-msgpack
    launchpad.net/mgo/bson

Your degoutils package is listed as being filled with experimental code, so maybe we should just copy what acme uses into this package? There's a lot of unneeded dependencies that come into play, it seems.

(The vendoring tool in question, gvt, always grabs all of the dependencies for a repo once it pulls in any package from it. So depending on github.com/hlandau/degoutils/net means that github.com/hlandau/degoutils/net/amqprpc comes into play.)

**Comment by jmhodges** [comment]
(Updated this issue to be more clear that I found this by vendoring github.com/hlandau/acme/acmeapi specifically)

**Comment by hlandau** [comment]
Created issues: https://github.com/vmihailenco/msgpack/issues/103 https://github.com/ugorji/go-msgpack/issues/16

Working on splitting up degoutils.

**Comment by hlandau** [comment]
degoutils dependency removed.
