### ISSUE TITLE
acmetool asks repeatedly for "Terms of Service" confirmation

### ISSUE THREAD

**Issue by processwired** [hlandau/acme#184]
I'm not sure if this is an issue related to acmetool, but I already googled for solutions and found nothing from "Let's encrypt" themself, so I guess I should ask here.

Let me say first that **acmetool is a great tool** - I use it for 7 months now and it never let me down.

Issue is: since some days ago, acmetool's cron job "/usr/bin/acmetool --batch reconcile" throws the following error message: 
> 20160721234602 [ERROR] acme.storageops: Target(mydomain.com;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: cannot prompt the user: currently non-interactive

So I called the command manually. acmetool outputs the "Terms of service" confirmation dialog then. After confirmation with return or "y" it asks for an email address. After that it seems to work fine and renews a certificate. The whole process is somewhat annoying, because it outputs the dialog for every single domain which has to be renewed  in a loop. Any ideas what's causing this? Or is this intended behaviour? 

thanks for any hints...

**Comment by hlandau** [comment]
This is caused by this issue with Let's Encrypt:
https://github.com/letsencrypt/boulder/issues/2066
It's been fixed and should be rolled out soon.

**Comment by bobelev** [comment]
Is there any workaround until it's not rolled out? Or I need to accept EULA and type emails for 20 domains?

**Comment by icb-** [comment]
Creating an [answer file](https://github.com/hlandau/acme/blob/master/_doc/response-file.yaml) at the default location with the answers to the prompts seems to work.

**Comment by processwired** [comment]
> Creating a response file at the default location with the answers to the prompts seems to work.
Great, **icb-**, that works for me too! "default location" does mean that the file should be placed in "/var/lib/acme/conf/responses", I guess.
I just changed two lines in the file:
- "acme-enter-email"
- "acmetool-quickstart-webroot-path": "/var/run/acme/acme-challenge"
I'm no expert at all, but that was working for me instantly.

**Comment by tomwaldnz** [comment]
I know this is marked as "closed" but it's still an issue. Is there any additional information about this, when Let's Encrypt might start working again? I'm getting daily emails about my certificates not renewing, though I have a month or so until it's a problem.

**Comment by hlandau** [comment]
Have you updated acmetool?
Have you run acmetool interactively to ensure any new ToS is agreed to?

**Comment by tomwaldnz** [comment]
Yes I'm on the latest acmetool. I just ran the command below and accepted the new TOS - I hadn't seen that recommended anywhere else thanks. It runs on a cron job, and I know it runs because I get emails when it fails, but when I [listed all the cron jobs on the system](http://stackoverflow.com/questions/134906/how-do-i-list-all-cron-jobs-for-all-users) I couldn't see what it run.

This seemed to work, the date on the live certificate is updated. I've tried it on a personal domain to see how it goes. It's behind CloudFlare so it's a bit tricky to see if the certificate has really renewed, but [ssh says it is](http://www.shellhacks.com/en/HowTo-Check-SSL-Certificate-Expiration-Date-from-the-Linux-Shell), so I think it's all sorted. Thanks for the help :)
```
/usr/local/bin/acmetool
/usr/local/bin/acmetool want example.com www.example.com
echo | openssl s_client -connect example.com:443 2>/dev/null | openssl x509 -noout -dates
```

**Comment by rfay** [comment]
The current TOS is https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf (not the one suggested in https://github.com/hlandau/acme/blob/master/_doc/response-file.yaml) 

I'm pretty sure the first simple thing to do is just run acmetool as root and answer the prompts for all your sites. However, I'm unable to get past it thinking I've provided the 2015 TOS now.

**Comment by hlandau** [comment]
Are you using the current version of acmetool, v0.0.56 or master?

**Comment by rfay** [comment]
Yeah, sorry I just discovered that my PPA config in /etc/apt/sources.list.d was lost so I was still at  0.0.50-1precise1 and apt-get upgrade still thought I had the latest.  I reinstalled the PPA and upgraded the acmetool package, and ran acmetool (with no args) to respond to the prompt, and everything upgraded fine. Sorry for the noise.
