### ISSUE TITLE
Import PEM-encoded account key

### ISSUE THREAD

**Issue by martinp** [hlandau/acme#187]
I have my existing account key stored as a PEM-encoded file. How can I use it/import it with acmetool?

**Comment by martinp** [comment]
I managed to convert my key into JWK and imported it with `import-jwk-account`. Maybe acmetool can support importing PEM-encoded keys directly as well.

**Comment by hlandau** [comment]
Implemented.

**Comment by dol** [comment]
Thank you for this. This option is missing in the man page.

**Comment by dol** [comment]
I created a PR https://github.com/hlandau/acme/pull/311
