### ISSUE TITLE
Failed to request certificate: cannot prompt the user: currently non-interactive

### ISSUE THREAD

**Issue by tomwaldnz** [hlandau/acme#188]
I've been using Acme for around seven months, and auto-renewal via cron seems to have worked fine since then - I've not had monitoring report any errors anyway. Today I got this error message by email.

I could probably dive in and renew certificates by hand, but they've got a little time until expiry I think, so instead I'll see if I can get the cron script working. This is on Amazon Linux, which is based on Centos, with Acme 0.53. Any suggestions how to resolve this?

20160729061702 [ERROR] acme.storageops: Target(example.com,www.example.com;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: cannot prompt the user: currently non-interactive
20160729061702 [ERROR] acme.storageops: Target(2.example.com,www.2.example.com;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: cannot prompt the user: currently non-interactive
20160729061702 [ERROR] acme.storageops: error while processing targets: the following errors occurred:
error satisfying Target(example.com,www.example.com;https://acme-v01.api.letsencrypt.org/directory;0): cannot prompt the user: currently non-interactive; 
error satisfying Target(2.example.com,www.2.example.com;https://acme-v01.api.letsencrypt.org/directory;0): cannot prompt the user: currently non-interactive
20160729061702 [ERROR] acme.storageops: failed to reconcile: the following errors occurred:
error satisfying Target(example.com,www.example.com;https://acme-v01.api.letsencrypt.org/directory;0): cannot prompt the user: currently non-interactive; 
error satisfying Target(2.example.com,www.2.example.com;https://acme-v01.api.letsencrypt.org/directory;0): cannot prompt the user: currently non-interactive
20160729061703 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:
error satisfying Target(example.com,www.example.com;https://acme-v01.api.letsencrypt.org/directory;0): cannot prompt the user: currently non-interactive; 
error satisfying Target(2.example.com,www.2.example.com;https://acme-v01.api.letsencrypt.org/directory;0): cannot prompt the user: currently non-interactive

**Comment by haraldkoch** [comment]
I suspect this is caused by / similar to #184?

**Comment by tomwaldnz** [comment]
Yes I think you're right, this is a duplicate. Thanks for pointing that out :)
