### ISSUE TITLE
Build run on FreeBSD not working

### ISSUE THREAD

**Issue by backstube** [hlandau/acme#189]
Hi,
I am having problems building acmetool on FreeBSD 10.3 from source code. This is what `make` spits out:

    root@host:~/Code/acme # make
    make: "/root/Code/acme/Makefile" line 19: Missing dependency operator
    make: "/root/Code/acme/Makefile" line 23: Need an operator
    make: "/root/Code/acme/Makefile" line 24: Missing dependency operator
    make: "/root/Code/acme/Makefile" line 26: Need an operator
    make: "/root/Code/acme/Makefile" line 27: Missing dependency operator
    make: "/root/Code/acme/Makefile" line 29: Need an operator
    make: "/root/Code/acme/Makefile" line 36: Missing dependency operator
    make: "/root/Code/acme/Makefile" line 39: Need an operator
    make: "/root/Code/acme/Makefile" line 42: Missing dependency operator
    make: "/root/Code/acme/Makefile" line 43: warning: duplicate script for target "ifeq" ignored
    make: "/root/Code/acme/Makefile" line 38: warning: using previous script for "ifeq" defined here
    make: "/root/Code/acme/Makefile" line 43: warning: duplicate script for target "(,1)" ignored
    make: "/root/Code/acme/Makefile" line 38: warning: using previous script for "(,1)" defined here
    make: "/root/Code/acme/Makefile" line 44: Need an operator
    make: Fatal errors encountered -- cannot continue
    make: stopped in /root/Code/acme

Obvious prerequisites `/usr/local/bin/bash` and `/usr/local/bin/go` are in place. I also gave `gnu-make` a try, I tweaked Makefile's path values to absolute paths -- without success. Does anyone know what's wrong here? Any tips on how to solve this issue? Thanks in advance.

**Comment by hlandau** [comment]
BSD make is very different from GNU make, and the same makefile can't realistically be made to work with both. For now, use the GOPATH-based build instructions:
```
mkdir foo
cd foo
export GOPATH=`pwd`
go get github.com/hlandau/acme/cmd/acmetool
sudo cp bin/acmetool /usr/local/bin/
```

gmake should work, so I'll look into that.

**Comment by hlandau** [comment]
Works for me if I change `SHELL := /bin/bash` to `SHELL := $(shell which bash)` and run `gmake`. Ensure bash is installed. Does this work?

**Comment by hlandau** [comment]
This fix is now in master.

**Comment by backstube** [comment]
Yes, it does. Thank you very much for your quick response and reaction.
