### ISSUE TITLE
CA selection dialog still contains an outdated and misleading reference to invitations in 0.12.0

### ISSUE THREAD

**Issue by kkofler** [hlandau/acme#19]
A nitpick, but arguably a usability issue: Even after commit be5595817b817fd96902f8480432326a8eaaa9eb, there is still:
https://github.com/hlandau/acme/blob/be5595817b817fd96902f8480432326a8eaaa9eb/cmd/acmetool/quickstart.go#L472
`Title: "Let's Encrypt Live Server - I have been invited and want live certificates"`
where "have been invited and" should probably be removed.

**Comment by hlandau** [comment]
Whoops. I'll fix that.
