### ISSUE TITLE
Question: It is really necessary keep separate folder per cert-domain for multidomain SANs

### ISSUE THREAD

**Issue by md2k** [hlandau/acme#190]
I found that when i generate multi-domain SAN certificate it creates separate Key-Cert folders per domain which was requested for certificate, maybe it is will be more logical to have only one folder for multi-domain certificates where directory is for primary domain, it not something about space, because this amount of data typically won't fill a disk space, but if i will have SAN for 20-30 domains i found that 20-30 folders of duplicate data not very useful.

Can be this done over some additional flag with `want` command at least if not way to do this behaviour by default?

**Comment by md2k** [comment]
P.S.  as i can se official certbot, keeps multidomain SAN certificates under primary domain (first domain from the wanted list)

**Comment by hlandau** [comment]
I'm unable to replicate this behaviour.
Running `acmetool want a.com b.com` should result in a structure like this:

```
live/a.com -> certs/abcd...
live/b.com -> certs/bcde...
certs/abcd.../{cert,chain,fullchain,url}
keys/bcde.../privkey
```

Are you sure you aren't confusing the symlinks and the certs directory?

**Comment by md2k** [comment]
I'll check and let you know, maybe you right and i been confused.

**Comment by abh** [comment]
Well, still ... I'm using a hook to install the certs into the configuration management system and the input to the hook is each name in the SAN so it's difficult (a bunch of extra work anyway) to only "install" one version of each cert.  The software (haproxy) doesn't seem to mind the duplicates, but it's a little silly.

**Comment by hlandau** [comment]
There's no such thing as an 'alternate name'. Only a set of names, none of which are more primary than the other.

You can readlink the symlink under live to get the cert ID, which is unique. Or you could maybe read the certificate and only process it if the SAN equals the common name, which should only be the case for one of the symlinks.
