### ISSUE TITLE
DNS Hook for anyone who need multi-domain SAN for domains with different DNS providers and accounts.

### ISSUE THREAD

**Issue by md2k** [hlandau/acme#193]
Not think that this is right place for it, so pardon if i doing it wrong.

This [dns.hook](https://github.com/md2k/acmetool_multidns_hooks) accomplish case when you have domains under different accounts and different providers, but want to have multi-domain SAN certificate which is include subdomains from those different providers/accounts.
Currently only CloudFlare and AWS Route53

**Comment by hlandau** [comment]
Thanks. I've added this to the links section of the user guide.
