### ISSUE TITLE
acmetool ≥ 0.0.55 cannot be distributed due to missing licenses

### ISSUE THREAD

**Issue by petercolberg** [hlandau/acme#195]
Building acmetool versions ≥ 0.0.55 from source requires  the new packages github.com/hlandau/goutils, github.com/hlandau/buildinfo, and github.com/hlandau/dexlogconfig, which currently do not contain a mention of their license (hlandau/goutils#1, hlandau/buildinfo#1, hlandau/dexlogconfig#1).

The missing licenses render acmetool unfit for distribution through third parties, e.g., Debian and Ubuntu.

**Comment by petercolberg** [comment]
I would be grateful to you if we can find a solution that lies within the restrictions of the Debian policy; which I have realized is a lot to ask for not having myself contributed new features or bug fixes to acmetool. I am thankful for all the work that you have put into acmetool including the comprehensive user’s guide and the always up-to-date packages for a range of distributions.

**Comment by hlandau** [comment]
Licence information is tracked via [RILTS](https://github.com/hlandau/rilts/blob/master/RILTS.md).
