### ISSUE TITLE
Q: is acmetool ready for SNI?

### ISSUE THREAD

**Issue by backstube** [hlandau/acme#202]
A short question for carification: is it possible to have `acmetool` handle with multiple domains on one host with only one IP address? I was able to bring up example.com on that box, but haven't had any success so far in repeating that with example.net, jabber.example.net, pad.example.net and more domains as well. Webserver is nginx.

Additionally, #72 to me indicates that SNI isn't ready so far. Also, SNI is not covered in User's Guide afaik.

**Comment by hlandau** [comment]
It supports SNI fine. The purpose of acmetool is to obtain certificates. No special support in a certificate is required to facilitate SNI; it needs to be supported by the web browser (basically all of them), and the webserver (basically all of them).

**Comment by backstube** [comment]
Ah, okay. Thanks for confirmation.
Currently, during example.net validation the example.com's certificate is being presented. Of course this mismatch raises errors. So best guess is that web server config is not entirely correct. Browsers are btw all perfectly SNI capable.
