### ISSUE TITLE
IPv6 address invalid hostname: "[2a03:4000:6:3064::1]"

### ISSUE THREAD

**Issue by Thermi** [hlandau/acme#204]
Hello,

When trying to run `acmetool want 2a03:4000:6:3064::1` with and without brackets around the IP address,
acmetool prints out the following warnings and does not accept the IP address.

```
20160911154245 [ERROR] acme.storage: failed to load target 2a03:4000:6:3064::1-gkde2faj7bbhfhil3atufydq6u: invalid target: 2a03:4000:6:3064::1-gkde2faj7bbhfhil3atufydq6u: invalid hostname: "2a03:4000:6:3064::1"
20160911154245 [ERROR] acme.storage: failed to load target 2a03:4000:6:3064::1-gkde2faj7bbhfhil3atufydq6u: invalid target: 2a03:4000:6:3064::1-gkde2faj7bbhfhil3atufydq6u: invalid hostname: "2a03:4000:6:3064::1"
```

Also, it does not clear up the files of such failed attempts from `desired/`.
I think that would be nice.
I know letsencrypt does not support certificates for IP addresses (yet?).

**Comment by hlandau** [comment]
To clarify, what you want is better error handling here, yes? Obviously this can't ever work.

**Comment by Thermi** [comment]
Yes. When there's that error, the file in `desired/` should not be created (or be deleted). The reason is that the mere existence of those files produces error on every call of `acmetool` and that's not pretty.
