### ISSUE TITLE
A systemd.timer and .service file

### ISSUE THREAD

**Issue by Thermi** [hlandau/acme#205]
I integrated acmetool into systemd using a .timer and .service unit on my server.

I'm showing them here to make it easier for others. Maybe you want to integrate them into the github.io page for acmetool.

```
[Unit]
Description = update Let's Encrypt certificates

[Service]
ExecStart=/usr/bin/acmetool --batch reconcile
ExecStartPost=/usr/bin/systemctl reload nginx
ExecStartPost=/usr/bin/cp /var/lib/acme/live/thermi.strangled.net/haproxy /var/lib/znc/.znc/certs/znc_whole_chain.pem
ExecStartPost=/usr/bin/chown znc:znc /var/lib/znc/.znc/certs/znc_whole_chain.pem
ExecStartPost=/usr/bin/chmod 600 /var/lib/znc/.znc/certs/znc_whole_chain.pem

PermissionsStartOnly=True
User=acme
Group=acme
PrivateTmp=True
PrivateDevices=True
ProtectSystem=True
ProtectHome=True
NoNewPrivileges=True

```

```
[Unit]
Description=Timer unit to update certificates every hour at 48 minutes
After=connection.service

[Timer]
OnCalendar = *-*-* *:48:00
Unit = acme.service
Persistent = True

[Install]
WantedBy=multi-user.target
```

**Comment by hlandau** [comment]
This would work better as a Gist. Make it one and I'll link to it.

**Comment by Thermi** [comment]
[Done.](https://gist.github.com/Thermi/05f2a2903dee6c37bbbb31405ee082d2)
In the text you're using to link to it, please tell the people to create a system user with `useradd -r -d /var/empty acme` first and to `chown -R acme:acme /var/lib/acme`
Also, the special commands in `acme.service` to `cp`, `chmod`, `chown` and reload services are obviously use case dependent.

**Comment by hlandau** [comment]
I've moved the third party resources [to the wiki](https://github.com/hlandau/acme/wiki/ThirdPartyResources), which should allow less friction in the future.

You should add the usage notes to the gist.

**Comment by Thermi** [comment]
Done and well appreciated.
