### ISSUE TITLE
file permissions for none-root users

### ISSUE THREAD

**Issue by brejoc** [hlandau/acme#206]
I've got a webserver that gets started with a "normal" user on port 3000, I'd like to use HTTPS, but with a default acmetool installation permissions are preventing this. Is there any way to change the permissions of the 'want' and 'renewal' process?

**Comment by hlandau** [comment]
You can run acmetool under whatever user you like. It doesn't chown files or anything, so it manages its state under the user it runs as.

If you don't run it as root, you'll probably need to specify a different state directory as you won't be able to run under `/var/lib/acme`.

If you really need to you can [override acmetool's permissions enforcement and optionally ask it to enforce ownership](https://github.com/hlandau/acme/blob/master/_doc/perm.example), but you shouldn't need to do this even in your case.

**Comment by brejoc** [comment]
Thanks @hlandau! This should indeed be enough for this case.
