### ISSUE TITLE
Reconcile fails in Ubuntu 14.04

### ISSUE THREAD

**Issue by dexafree** [hlandau/acme#21]
I tried both the binary and compiling the source code (`make && make install`) with Go 1.5.2 installed.

If I run `acmetool quickstart` it guides me correctly and everything goes great.

But when I try to `acmetool want myserver.com` , it always fails with a message that goes like:

```
YYYYMMDDHHmm [CRITICAL] acmetool: fatal: reconcile: failed all combinations
```

I've tried googling for that error, but I have found nothing.

Any help?

**Comment by hlandau** [comment]
You can increase logging severity with `--xlog.severity=debug`. This error means the ACME server can't validate your hostname, so double check your chosen challenge response method is set up correctly.

**Comment by dexafree** [comment]
Ok. Solved.

I thought I had disabled nginx (so acme can listen to port 80), but in the log I could see it actually wasn't.
Now it worked, thanks!
