### ISSUE TITLE
fdb file permission checking too strict

### ISSUE THREAD

**Issue by Mrten** [hlandau/acme#216]
I'd like to secure the state directory more, and the `keys` directory less, to sync keys with another server (via a user in the `acme` group). However, every run of acmetool resets the permissions:
```
20161104000825 [WARN] fdb: "." has wrong mode -rwxr-x---, changing to -rwxr-xr-x
20161104000825 [WARN] fdb: "keys" has wrong mode -rwxr-x---, changing to -rwx------
```
Can the resetting of permissions be made a bit more liberal?

**Comment by hlandau** [comment]
You can use a permissions file to customise the permissions enforcement.

https://github.com/hlandau/acme/blob/master/_doc/perm.example
