### ISSUE TITLE
Please mark the acme binary with paxtcl

### ISSUE THREAD

**Issue by jvoisin** [hlandau/acme#217]
It seems that acme wants a `RWX` mapping, and thus is killed by grsecurity:

```bash
[89066.968241] grsec: From X.X.X.X: denied RWX mprotect of /usr/bin/acmetool by /usr/bin/acmetool[acmetool:6638] uid/euid:0/0 gid/egid:0/0, parent /bin/zsh[zsh:4430] uid/euid:0/0 gid/egid:0/0
```

This is kind of expected, because acmd is written and Go, and it doesn't play nice with [PaX]( https://github.com/golang/go/issues/47 ). It seems that the *solution* is to mark the binary with `paxctl`. care to do it?

**Comment by hlandau** [comment]
According to https://github.com/golang/go/issues/47 this already should be fixed...
Blocked on https://github.com/travis-ci/apt-package-whitelist/issues/3500.

**Comment by hlandau** [comment]
Is this still an issue?

**Comment by jvoisin** [comment]
Now that grsecurity isn't available to everyone for free anymore, I doubt that I lot of people will be bothered by it anyway.
