### ISSUE TITLE
parseperm_test.go fails when built with gccgo on mips

### ISSUE THREAD

**Issue by petercolberg** [hlandau/acme#219]
When built with gccgo 6.2.0 on mips ([build log](https://buildd.debian.org/status/fetch.php?pkg=acmetool&arch=mips&ver=0.0.58-3&stamp=1479677902)) or mips64el ([build log](https://buildd.debian.org/status/fetch.php?pkg=acmetool&arch=mips64el&ver=0.0.58-3&stamp=1479696865)), the test suite fails with
```
=== RUN   TestParsePerm
--- FAIL: TestParsePerm (0.00s)
	parseperm_test.go:41: error parsing permissions: line 6: invalid UID: "root": because this binary was built without cgo, UIDs/GIDs must be specified numerically and not as names
FAIL
FAIL	github.com/hlandau/acme/fdb	1.456s
```

**Comment by hlandau** [comment]
Thanks for the report.
