### ISSUE TITLE
directory in live/ or otherwise per collection

### ISSUE THREAD

**Issue by Mrten** [hlandau/acme#220]
If you request multiple domains in a single file in `desired/`, you get a different symlink in `live/` per domain requested to the same directory in `certs/`. The name of the directory in `certs/` however it not readily linked to the name of the file in `desired/`.

I'd like to not loose the connection of the file in `desired/` to the requested certificates, as I'm not really interested in the certificate for the domain but am interested in the certificate for the group of domains. 

The symlinks in `live/` would conflict when a domain would be in multiple certs but I don't know whether lets-encrypt allows that, and that's not what my inquiry is about.

**Comment by hlandau** [comment]
Implementing this would be contrary to the design of acmetool. There may be multiple `desired` files which a given certificate satisfies, and a `desired` file may be satisfied by multiple certificates.
