### ISSUE TITLE
Allow renewal margin to be configured

### ISSUE THREAD

**Issue by Mrten** [hlandau/acme#221]
Currently the renewal margin is fixed in the code to 30 days, I saw issue #93 where you lowered it even further.

I'd like to be able to set it to 60 days for testing purposes (or even 89 when running with the staging servers), to test whether automatic renewal and subsequent distribution over my servers succeeds, and if not I'd have then I'd have 60 days to find me another registrar. 

Will you consider this?

**Comment by hlandau** [comment]
Implemented for v0.2.1.
