### ISSUE TITLE
reconcile only one target?

### ISSUE THREAD

**Issue by Mrten** [hlandau/acme#222]
```
root@acme:/var/lib/acme/desired# ls | wc
     65      65    1249
```
and there's a problem with it, however:
```
root@acme:/var/lib/acme/desired# acmetool  --xlog.severity=debug 2>&1 | wc
  27224  581715 15130356
```
the clue to what exactly is amiss is hidden in between 27000 other lines. So, the logging is way too chatty (I really do not care about fdb, usually), but that wouldn't matter if there was a way to reconcile only one target.

Currently I hack around that by removing 64 desired files, but reconciling only one target would be _very_ useful for debugging.

**Comment by hlandau** [comment]
Implemented for v0.2.1.
