### ISSUE TITLE
Self-signed certs in case of failures

### ISSUE THREAD

**Issue by artem-sidorenko** [hlandau/acme#231]
it would be great of acmetool would generate some self-signed certificates if something goes wrong. Why?

If the initial `acmetool want example.com` fails for some reason - there is no certificate and key, so a usual daemon would fail to start/reload.

This case is especially interesting for chef/puppet/ansible automation, where you you might want to keep your web daemon running still if acmetool fails.

**Comment by artem-sidorenko** [comment]
If I understand [this right](https://certbot.eff.org/faq/#can-i-issue-a-certificate-without-bringing-down-my-web-server), it looks like a basic functionality of official certbot client

**Comment by hlandau** [comment]
Duplicate of #37.
