### ISSUE TITLE
Acmetool does not reconcile

### ISSUE THREAD

**Issue by simonszu** [hlandau/acme#232]
Hi,

since some days i get Let's encrypt certificate expiry notices. I checked the certificate in question and noticed that it does indeed expire in 15 days. I am quite sure that this should not happen, so i want to examine the cronjob which should call the reconcile command, but i cannot find it. 
I have a debian system. 
I searched for the cron file in the /etc/cron.* directories, but nothing. I only have a reference in /var/spool/crontab. 

But, on a second host, with almost identical setup, i have no cron files in these directories as well, and all certs get reconciled. 
I have already removed and reinstalled acmetool on the first failing host, but the expiry notices still come in. On the other hand, when i call acmetool reconcicle manually, all certs get renewed. 

So, where can i start debugging?

**Comment by snabb** [comment]
This can happen at least in the following situation:
1) install acmetool from debian/ubuntu repositories
2) add hlandau ppa
3) run apt upgrade

Debian package includes the necessary parts for running acmetool periodically but hlandau ppa deb does not include them. Thus upgrading to the ppa version easily breaks existing setup.
