### ISSUE TITLE
Add LICENSE file to project

### ISSUE THREAD

**Issue by kpcyrd** [hlandau/acme#235]
I'm trying to `install(1)` the `LICENSE` to `/usr/share/licenses/acmetool/LICENSE` which obviously fails because the file does not exist. :)

Could you please either add a LICENSE or COPYING file to the project?

**Comment by kpcyrd** [comment]
@hlandau I was about to file an issue about the missing license and noticed I already did. Should I just PR the MIT license?

**Comment by haraldkoch** [comment]
The license is clearly documented in the README, including a link to a downloadable copy. If you're doing this as part of a packager, you could download the license file yourself?

**Comment by kpcyrd** [comment]
Correct, this is for packaging. Is there a reason why this is done in a non-standard way, especially with a license that short? The text that describes how to acquire the license is over 10% the size of the full license file.

**Comment by hlandau** [comment]
Licence is mentioned in the README and more rigorously in commits via [RILTS](https://github.com/hlandau/rilts).
