### ISSUE TITLE
redirector: unable to drop privileges (Ubuntu trusty)

### ISSUE THREAD

**Issue by hase-berlin** [hlandau/acme#246]
On my trusty old server running trusty (pun intended), the redirector immediately terminates, complaining about being unable to drop privileges.
```
root@server:~# acmetool redirector --service.gid=daemon --service.uid=daemon                
Error in service: Failed to drop privileges: ensure no privs failed: still have non-zero UID or GID or capabilities

```
Adding the --service.daemon flag changes behaviour: the command prompt immediately returns, no error visible. But it is still there:
``` 
root@server:~# strace -f acmetool redirector --service.gid=daemon --service.uid=daemon --service.daemon
[...]
[pid 23167] write(2, "Error in service: Failed to drop"..., 116) = 116
[pid 23167] exit_group(1)               = ?
[pid 23172] +++ exited with 1 +++
[...]
```
Using uid/gid hase:hase (an unpriviledged user) does not change the behaviour.
Adding --service.fork changes behaviour: 
```
root@server:~# acmetool redirector --service.gid=daemon --service.uid=daemon --service.fork
root@server:~# acmetool: error: unexpected $*_FORKED_*$, try --help
```
The process detaches, I iimmediately get a new shell prompt. The error is printed probably on stderr by the daemon in the background.
What is happening here, what am I doing wrong?

I probably can circumvent the issue by moving to another verification method, but I like the redirector feature :-)
merci
hase

**Comment by rysiekpl** [comment]
There are problems with dropping privileges in go, apparently:
 - golang/go#13838
 - golang/go#1435

Potential (partial) solution:
https://github.com/golang/go/issues/1435#issuecomment-173804075

**Comment by hlandau** [comment]
Trusty has Go1.2, which is now very old. Closing.
