### ISSUE TITLE
Get well-known challenge tokens without issuing certificates?

### ISSUE THREAD

**Issue by taylorotwell** [hlandau/acme#247]
Hello,

Is it possible to have the client issue the token I need to place in well-known challenge files on my servers and then once I get that token in place on all my servers I can separately tell the client to have LetsEncrypt verify the challenge and issue the certificates?

**Comment by hlandau** [comment]
You can use the hook method to automate this. https://hlandau.github.io/acme/userguide#challenge-hooks
