### ISSUE TITLE
Is using /var/run to store challenges a security issue?

### ISSUE THREAD

**Issue by hlandau** [hlandau/acme#25]
Since /var/run is a tmpfs on modern systems, this could be an issue, especially if an attacker could use a symlink to cause something else to be overwritten as root. Or if someone symlinked to it from their web directory, it could be used to serve data under .well-known/acme-challenge.

Currently the redirector GID option and the webroot depositor in the HTTP responder try to be a bit paranoid about this by refusing to follow symlinks, but the semantics of O_NOFOLLOW mean that isn't 100% effective, because it only restricts the last path component.

Maybe /var/run/acme/acme-challenge should be moved to /var/cache/acme/acme-challenge or /var/spool/acme/acme-challenge to reduce the attack surface.

**Comment by grawity** [comment]
"It's a tmpfs" does not automatically make it any more vulnerable than any other filesystem; `/var/run` is still writable _only by root_ in any default setup. (Otherwise you'd have already heard everyone yelling about it years ago.)
