### ISSUE TITLE
access rights for exim?

### ISSUE THREAD

**Issue by hendriktews** [hlandau/acme#254]
Thanks a lot for this great tool!

I am not sure if the following is only a question for better documentation or a problem report.

I want to use the certificates for exim and dovecot. Dovecot is no problem, because it reads the private key before it drops the privileges. However, exim wants to read the private key as unprivileged exim user (Debian-exim on Debian). I therefore changed the permissions for the private key and the directories on the path to g+r, respectively g+x and put them into the exim group.

This worked fine for one day, until acmetool started as cron job and changed the permissions back.

Is there a way to configure acmetool such that an unprivileged exim user can read the private key? I am using "acmetool Debian version 0.0.58-4~bpo8+1", if that makes a difference.

Hendrik

**Comment by icb-** [comment]
Look at the [`conf/perm`](https://github.com/hlandau/acme/blob/master/_doc/perm.example) file. You can specify permissions and ownership there.

**Comment by hlandau** [comment]
icb- is right, use conf/perm. Closing.

**Comment by hendriktews** [comment]
Thanks for the hint, it works fine.

H.
