### ISSUE TITLE
Needs a little more verbose error handling

### ISSUE THREAD

**Issue by simonszu** [hlandau/acme#27]
I am currently testing acmetool with a domain i am supposing is rate limited, since i fired too many requests with it, because i couldn't figure how to properly use the "official" client. 
However, i am unsure if the domain is still in rate limiting, or will be accepted by the letsencrypt-servers again. 
However, testing it with acmetool results in `20151207111617 [CRITICAL] acmetool: fatal: reconcile: failed all combinations` which seems to be a general exception in [solver/respond.go](https://github.com/hlandau/acme/blob/master/solver/respond.go). So, for now, i am unsure if my combination of acmetool-nosudo-webroot is faulty or if my domain is still not accepted by LE's servers. A little more verbosity in error-handling would be great.

**Comment by hlandau** [comment]
You can pass `--xlog.severity=debug`, but yes, this needs improvement.

**Comment by hlandau** [comment]
This has been enhanced a bit. Now, an error meeting a target won't block trying to meet other targets, and the list of errors as a whole will be returned as one at the end of the process. Will be in v0.0.20. I'm sure there's still more to do, though, so leaving this open.
