### ISSUE TITLE
Regression in Go 1.7 affecting DNS resolution

### ISSUE THREAD

**Issue by gdetrez** [hlandau/acme#271]
I have timeout issues getting certificate that I suspect are related to https://github.com/golang/go/issues/16865. As far as I understood, there's a regression in Go 1.7 that affects DNS queries which is fixed in Go 1.7.1. 
The last two releases of acmetool are affected (0.0.58 and 0.0.59) as they were built with 1.7, that also seems to includes (at least) the debian packages.

I managed to make it work by using acmetools 0.0.57 but it might be helpful for others who might encounter the same problem to rebuild the packages with Go 1.7.1 to fix the problem.

Thanks for making a very useful tool!

**Comment by hlandau** [comment]
v0.0.61.
