### ISSUE TITLE
Incorrect accounts directory structure in specification 

### ISSUE THREAD

**Issue by F30** [hlandau/acme#272]
The ACME State Storage Specification in "_doc/SCHEMA.md" describes the contents of the "accounts" directory like this:

>     accounts/
>       (account ID)/
>         privkey           ; PEM-encoded account private key

> ### accounts
> An ACME State Directory MUST contain a subdirectory "accounts" which contains account-specific information. It contains zero or more subdirectories, each of which relates to a specific account. Each subdirectory MUST be named after the Account ID.

The actual acmetool implementation, on the other hand, creates and expects a structure like this:

    accounts/
      (URL-encoded provider URL without the protocol portion)/
        (account ID)/
          privkey

Without the additional layer for the provider URL, account keys will not be found by acmetool. The spec also says something about how clients "should generate a new account key and store it for that provider URL", but without the provider directory it remains unclear how that is supposed to work.

**Comment by hlandau** [comment]
This is consistent with the definition of "Account ID" in the specification:
https://github.com/hlandau/acme/blob/master/_doc/SCHEMA.md#identifiers
