### ISSUE TITLE
acmetool Hangs / Timeout.

### ISSUE THREAD

**Issue by suwalski** [hlandau/acme#275]
I'm trying to create a new a new certificate with acmetool. I don't have HTTPS configured yet, and the firewall is set to drop port 443 before it's set up.

This shows a bug in acmetool where it seems hung,  but it actually takes forever (13 minutes) to time out. At first I thought it was an outright hang, but when I got back to my desk it had actually completed.

  (...)
  20170920170624 [DEBUG] acme.storageops: trying to obtain authorization for "www.foo.com"
  20170920170624 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/new-authz
  20170920170625 [DEBUG] acme.api: response: &{201 Created 201 HTTP/1.1 1 1 map[Server:[nginx] Content-Type:[application/json] Content-Length:[994] Location:[https://acme-v01.api.letsencrypt.org/acme/authz/HASH] Strict-Transport-Security:[max-age=604800] Date:[Wed, 20 Sep 2017 21:06:25 GMT] Boulder-Requester:[21572975] X-Frame-Options:[DENY] Link:[<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"] Replay-Nonce:[nFndecIVlyASxcR3E13iSOOxUHyc2IJWYlzExHWD-v0] Expires:[Wed, 20 Sep 2017 21:06:25 GMT] Cache-Control:[max-age=0, no-cache, no-store] Pragma:[no-cache] Connection:[keep-alive]] 0xc420378580 994 [] false false map[] 0xc4200f13b0 0xc420394fd0} <nil>
  20170920170625 [DEBUG] acme.solver: attempting challenge type tls-sni-01
  20170920170625 [DEBUG] acme.responder: failed to start TLS-SNI listener: listen tcp :443: bind: address already in use
  20170920170625 [DEBUG] acme.hooks: calling hook script: /etc/acme/hooks/haproxy
  20170920170625 [DEBUG] acme.hooks: calling hook script: /etc/acme/hooks/reload
  20170920171908 [DEBUG] acme.responder: tls-sni-01 self-test failed: dial tcp 12.222.211.61:443: getsockopt: connection timed out
  20170920171908 [DEBUG] acme.hooks: calling hook script: /etc/acme/hooks/haproxy
  20170920171908 [DEBUG] acme.hooks: calling hook script: /etc/acme/hooks/reload
  20170920171908 [DEBUG] acme.solver: challenge start failed: dial tcp 12.222.211.61:443: getsockopt: connection timed out
  20170920171908 [DEBUG] acme.solver: attempting challenge type http-01
  20170920171908 [DEBUG] acme.responder: failed to listen on [::]:80: listen tcp [::]:80: bind: address already in use
  20170920171908 [DEBUG] acme.responder: failed to listen on :80: listen tcp :80: bind: address already in use
  20170920171908 [DEBUG] acme.responder: failed to listen on [::1]:402: listen tcp [::1]:402: bind: cannot assign requested address
  20170920171908 [DEBUG] acme.responder: listening on 127.0.0.1:402
  20170920171908 [DEBUG] acme.responder: failed to listen on [::1]:4402: listen tcp [::1]:4402: bind: cannot assign requested address
  20170920171908 [DEBUG] acme.responder: listening on 127.0.0.1:4402
  20170920171908 [DEBUG] acme.responder: writing 2 webroot challenge files
  (...)

Surely, the timeout on the SNI check should be at most a minute. Since there was no progress shown, there wasn't even anything to indicate that it's waiting on a test.

**Comment by hlandau** [comment]
The debug output indicates that the long delay occurred while executing the notify script, which basically means it took that long to reload/restart the webserver.
