### ISSUE TITLE
Unable to enter information during quickstart

### ISSUE THREAD

**Issue by alesju** [hlandau/acme#276]
I'm not sure how to best explain this issue, but it appears that there's a bunch of progression bars that messes up the quickstart. When I try to enter my email I can enter 1 letter, any next letter overwrites the previous one.

See this image for clues:
https://puu.sh/xG5zn/1d0f7ba319.png

This is on Ubuntu 16.04 using PPA:
apt-cache policy acmetool
acmetool:
  Installed: 0.0.61-1xenial1
  Candidate: 0.0.61-1xenial1

**Comment by reisub** [comment]
@alesju you can work around this issue by doing `apt-get install dialog` before the quickstart.
