### ISSUE TITLE
Fatal on FreeBSD 11.1 inside jail

### ISSUE THREAD

**Issue by satriani-vai** [hlandau/acme#278]
acmetool: fatal: couldn't complete registration: Get https://acme-v01.api.letsencrypt.org/directory: x509: failed to load system roots and no roots provided

**Comment by hlandau** [comment]
This is an issue with Go, since the Go standard library is responsible for loading CA certificates from the system. Are you sure that your system has CA certificates installed?

**Comment by lambdaupb** [comment]
You need to install the ca roots first using:

`pkg install ca_root_nss`
