### ISSUE TITLE
Problems with webroot

### ISSUE THREAD

**Issue by simonszu** [hlandau/acme#29]
Hi,

with your help and the mention of `--xlog.severity=debug` in Issue #27 I managed to dig a little deeper into my problems of requesting certificates. I have configured acmetool to use the webroot-method during quickstart setup, and created a `/var/run/acme/acme-challenge/` directory for which the `acme` user has full access rights. My nginx is configured to serve this directory on challenge requests. 
However, it just isn't working. Is acmetool requested to delete the challenges after presenting them to the servers? Because the directory is empty...

And the debug output is strange as well. Here it is:

    20151207135239 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/directory
    20151207135239 [DEBUG] acme.api: response: &{200 OK 200 HTTP/1.1 1 1 map[Expires:[Mon, 07 Dec 2015 12:52:39 GMT] Cache-Control:[max-age=0, no-cache, no-store] Pragma:[no-cache] Date:[Mon, 07 Dec 2015 12:52:39 GMT] Server:[nginx] Content-Type:[application/json] X-Frame-Options:[DENY] Connection:[keep-alive] Content-Length:[263] Replay-Nonce:[UMkeqsvY1jKa3g_jozGKhoFXbUndeTLkwh-kv_itvxo] Strict-Transport-Security:[max-age=604800]] 0xc82035c140 263 [] false map[] 0xc82030e8c0 0xc8202173f0} <nil>
    20151207135239 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/new-reg
    20151207135239 [DEBUG] acme.api: response: &{409 Conflict 409 HTTP/1.1 1 1 map[Cache-Control:[max-age=0, no-cache, no-store] Server:[nginx] Content-Length:[94] Location:[https://acme-v01.api.letsencrypt.org/acme/reg/54081] Replay-Nonce:[reOzzmScj6BGqJeXl_eRFy3lmr4Quady0XLVoBgKYHE] Content-Type:[application/problem+json] Expires:[Mon, 07 Dec 2015 12:52:39 GMT] Pragma:[no-cache] Date:[Mon, 07 Dec 2015 12:52:39 GMT]] 0xc820406180 94 [] true map[] 0xc8203307e0 0xc8202173f0} <nil>
    20151207135239 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/reg/54081
    20151207135240 [DEBUG] acme.api: response: &{202 Accepted 202 HTTP/1.1 1 1 map[Connection:[keep-alive] Server:[nginx] Content-Type:[application/json] Content-Length:[583] Link:[<https://acme-v01.api.letsencrypt.org/acme/new-authz>;rel="next" <https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf>;rel="terms-of-service"] Replay-Nonce:[R3l9epz_1EnPYwvRTzYbpYaVrDrHU7ufEcHt7ZvnARE] Date:[Mon, 07 Dec 2015 12:52:40 GMT] Expires:[Mon, 07 Dec 2015 12:52:40 GMT] Cache-Control:[max-age=0, no-cache, no-store] Pragma:[no-cache]] 0xc8201e0bc0 583 [] false map[] 0xc820106460 0xc8201c8580} <nil>
    20151207135240 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/directory
    20151207135240 [DEBUG] acme.api: response: &{200 OK 200 HTTP/1.1 1 1 map[Server:[nginx] Content-Type:[application/json] X-Frame-Options:[DENY] Expires:[Mon, 07 Dec 2015 12:52:40 GMT] Connection:[keep-alive] Content-Length:[263] Replay-Nonce:[7P_CbwJZELC9mywMqnf1L0QKOQanxP71sR4yeNRxrRI] Strict-Transport-Security:[max-age=604800] Cache-Control:[max-age=0, no-cache, no-store] Pragma:[no-cache] Date:[Mon, 07 Dec 2015 12:52:40 GMT]] 0xc8204e0080 263 [] false map[] 0xc8203308c0 0xc8201c8580} <nil>
    20151207135240 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/new-authz
    20151207135240 [DEBUG] acme.api: response: &{201 Created 201 HTTP/1.1 1 1 map[Content-Length:[568] Location:[https://acme-v01.api.letsencrypt.org/acme/authz/fHJ0-wMCapI1bWOjMfbhPQu4rrQpRO5IHxTim_i5q0w] X-Frame-Options:[DENY] Strict-Transport-Security:[max-age=604800] Expires:[Mon, 07 Dec 2015 12:52:40 GMT] Pragma:[no-cache] Connection:[keep-alive] Server:[nginx] Content-Type:[application/json] Link:[<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"] Replay-Nonce:[59Mt6eafpL-Us05QW17rjwImUcHwQd8rSjdcuiDnSBY] Cache-Control:[max-age=0, no-cache, no-store] Date:[Mon, 07 Dec 2015 12:52:40 GMT]] 0xc8203800c0 568 [] false map[] 0xc82044c000 0xc8201c8580} <nil>
    20151207135240 [DEBUG] acme.solver: attempting challenge type tls-sni-01
    20151207135240 [DEBUG] acme.solver: challenge start failed: listen tcp :443: bind: permission denied
    20151207135240 [DEBUG] acme.solver: attempting challenge type http-01
    20151207135240 [DEBUG] acme.responder: failed to listen on :80: listen tcp :80: bind: permission denied
    20151207135240 [DEBUG] acme.responder: failed to listen on 127.0.0.1:402: listen tcp 127.0.0.1:402: bind: permission denied
    20151207135240 [DEBUG] acme.responder: failed to listen on [::1]:402: listen tcp [::1]:402: bind: permission denied
    20151207135240 [DEBUG] acme.responder: http-01 self test
    20151207135240 [INFO] acme.responder: http-01 self test failed: non-200 status code when doing self-test
    20151207135240 [DEBUG] acme.solver: challenge start failed: non-200 status code when doing self-test
    20151207135240 [CRITICAL] acmetool: fatal: reconcile: failed all combinations

I am a little unsure why acmetool tries to bind on :80 or :402. This should be the behaviour when running acmetool as a redirector or with nginx proxying the requests to acmetool. So why does acmetool try to bind here? Is it some kind of fallback method if webroot method fails? But i have honestly no idea why webroot method fails. The nginx logfile states that there was a request by "Let's Encrypt validation server" on a certain challenge which was answered by my nginx with an HTTP 200 answer. 

I have double-checked the procedure with the proxy method, i got a proper handshake and a response from the LE server, so maybe the webroot is some kind of buggy?

**Comment by hlandau** [comment]
When acmetool asks you what method you want to use in the quickstart, it's actually a trick. If you select webroot it asks you for a path, and if you select redirector and use systemd it asks you if you want to install it as a service, but otherwise it doesn't record your choice in any way.

acmetool's strategy is to attempt anything that might possibly work, then try and query itself on the hostname you're requesting a certificate for to satisfy itself that it's working properly. It thus tries to bind to port 80 (the listen method), 402, 4402 (proxy method). It puts challenges in /var/run/acme/acme-challenge, as well as any other webroot directory you configure. It then self-tests.

So these failed binding attempts are normal.

Challenge files are deleted after use, yes. Since you mention an `acme` user I assume you're using the non-root setup. I assume you've tested that the acme user can write to the directory, and that the web server serves files correctly:

```
$ sudo -u acme -i
$ echo foo > /var/run/acme/acme-challenge/test
$ curl -i http://localhost/.well-known/acme-challenge/test
```

I should probably add more logging for the writing of webroot files, in case it fails.

**Comment by hlandau** [comment]
If you're feeling adventurous and don't mind building yourself, you could stick some debugging statements in `responder/http.go`. I'll do this in the next release. Here I've amended `webrootWriteChallenge`:

```go
  if err != nil {
    log.Errore(err, "failed to open webroot file ", fn)
    continue
 }
```

Commenting the os.Remove line in `webrootRemoveChallenge` might also be helpful.

**Comment by simonszu** [comment]
I think i fixed it. It was a misconfiguration of my web server. After i made sure the request via `curl -i` was successful, the request via the acmetool-LE-handshake was successful as well.
