### ISSUE TITLE
using in docker environment

### ISSUE THREAD

**Issue by garyhooper** [hlandau/acme#297]
I'm wanting to use acmetool with a reverse-proxy and nginx in a docker environment. For certificate renewal, how can I trigger nginx to reload when it's in a different docker container?  Any advice/examples would be very much welcomed.

**Comment by emcniece** [comment]
Have a look at https://github.com/CausticLab/rgon-proxy - we use acmetool in exactly this scenario.

Our particular flavour of environment is Rancher, and we use [Rancher-Gen](https://github.com/CausticLab/go-rancher-gen) to detect container IP changes and rebuilt `nginx.conf`. After the Nginx config updates, we use [rgon-exec](https://github.com/CausticLab/rgon-exec) to trigger an Nginx reload via the Rancher API.

**Comment by garyhooper** [comment]
Thanks...will take a look.
