### ISSUE TITLE
Docs for actual changes made by quickstart?

### ISSUE THREAD

**Issue by mafrosis** [hlandau/acme#33]
A really great little tool! Thanks.

I ran `quickstart` and everything is working wonderfully.  I now need to know where `acmetool` has stored all it's config, so I can automate the install process Did I miss something in the docs?

**Comment by hlandau** [comment]
acmetool stores its state in `/var/lib/acme`. ([The format for this directory is documented here.](https://github.com/hlandau/acme/blob/master/_doc/SCHEMA.md)) It also installs default notification hooks (shell scripts it invokes to reload webservers) in `/usr/lib/acme/hooks` (or `/usr/libexec/acme/hooks` for distros which use libexec). It will optionally also install a cronjob, either in `/etc/cron.d` (if run as root) or using the `crontab` command (if you are using non-root operation). tt can optionally install a service file for the redirector in `/etc/systemd/system` if you are using systemd.

**Comment by mafrosis** [comment]
@hlandau The quickstart response file is another nice little feature - I'll use that for automated installs. Thanks for the detail on what's happening behind the scenes

**Comment by mafrosis** [comment]
One quick note on the response file at https://github.com/hlandau/acme/blob/master/_doc/response-file.yaml - it doesn't have an entry for the "Enter Webroot Path" question.

**Comment by hlandau** [comment]
That's "acmetool-quickstart-webroot-path". Make sure you set "acmetool-quickstart-choose-method" to "webroot".

By the way, you can also just put the path in the file `/var/lib/acme/conf/webroot-path`. acmetool aims to minimise the use of state and be transparent in the state it does use.
