### ISSUE TITLE
Account ID is impossible to obtain (needed for CAA; workaround detailed)

### ISSUE THREAD

**Issue by paulfertser** [hlandau/acme#351]
With the current code it does not seem possible to get the "Account ID" anyhow. Debug mode doesn't show API requests and responses so `Boulder-Requester` field is not visiblle, and no other method is offered.

This is needed to add domain-level restrictions by using a CAA record with which you can tell CAs which accounts specifically are permitted to obtain new certificates for the domain. Lack of CAA is what allowed MITM compromise of Hetzner/Linode jabber.ru server: https://notes.valdikss.org.ru/jabber.ru-mitm/ .

I used acme.sh like this to get Account ID from `location` header from the log: `./acme.sh --register-account --log-level 3 --accountkey privkey --home `pwd` --log acme.sh.log --server https://acme-v02.api.letsencrypt.org/directory` (privkey was copied from `/var/lib/acme/accounts/acme-v02.api.letsencrypt.org%2fdirectory/*/` . For good measure I added `, \"onlyReturnExisting\": true` to `regjson`.

**Comment by asalmela** [comment]
Doesnt `acmetool account-url`  show this?

**Comment by paulfertser** [comment]
Hm, guess it does, thank you very much for the hint. I am kinda stuck on Debian oldstable and it has older version. I didn't notice that but I checked if the binaries in this repo releases or actions are newer and they were not.
