### ISSUE TITLE
Unable to get webroot working

### ISSUE THREAD

**Issue by mafrosis** [hlandau/acme#36]
A response file:

    acmetool-quickstart-choose-server: https://acme-v01.api.letsencrypt.org/directory
    acmetool-quickstart-choose-method: webroot
    acme-enter-email: username@domain.net
    acmetool-quickstart-complete: true
    acmetool-quickstart-webroot-path: /srv/app/dirname/.well-known/acme-challenge
    acmetool-quickstart-install-cronjob: true
    acmetool-quickstart-install-haproxy-script: false
    acmetool-quickstart-install-redirector-systemd: false
    acmetool-quickstart-rsa-key-size: 4096
    acme-agreement:https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf: true

Running `quickstart` gives me this:

    > sudo acmetool quickstart --response-file=/tmp/responses.yaml
    [-------------------------------------------------------------------] 0.00 % 12s

Running `want` gives me this - which says it fails to bind 80 & 443, which it shouldn't do under webroot mode. Am I missing something here?

    > sudo acmetool --xlog.severity=debug want subdomain.domain.com
    20151208164026 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/directory
    20151208164027 [DEBUG] acme.api: response: &{200 OK 200 HTTP/1.1 1 1 map[Cache-Control:[max-age=0, no-cache, no-store] Pragma:[no-cache] Date:[Tue, 08 Dec 2015 16:40:27 GMT] Connection:[keep-alive] Content-Type:[application/json] Replay-Nonce:[P9QJjb7bz0bWGZzKL2Q3W3voCwjRsWrjKiq7GdIUPwE] X-Frame-Options:[DENY] Strict-Transport-Security:[max-age=604800] Expires:[Tue, 08 Dec 2015 16:40:27 GMT] Server:[nginx] Content-Length:[263]] 0xc82017ab80 263 [] false map[] 0xc820692000 0xc820096dc0} <nil>
    20151208164027 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/new-reg
    20151208164027 [DEBUG] acme.api: response: &{409 Conflict 409 HTTP/1.1 1 1 map[Replay-Nonce:[mApHfKp8tas_xOT-pwKUcrY22HXRdWioDZ-Z58WSFj8] Cache-Control:[max-age=0, no-cache, no-store] Pragma:[no-cache] Date:[Tue, 08 Dec 2015 16:40:27 GMT] Location:[https://acme-v01.api.letsencrypt.org/acme/reg/61271] Content-Type:[application/problem+json] Content-Length:[94] Expires:[Tue, 08 Dec 2015 16:40:27 GMT] Server:[nginx]] 0xc8206a7f80 94 [] true map[] 0xc8204d3a40 0xc820096dc0} <nil>
    20151208164027 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/reg/61271
    20151208164027 [DEBUG] acme.api: response: &{202 Accepted 202 HTTP/1.1 1 1 map[Server:[nginx] Content-Type:[application/json] Replay-Nonce:[1j74g_vMHXem5uj9e8ozawAIUtgtQBcFgRFIsfh1K3U] Expires:[Tue, 08 Dec 2015 16:40:27 GMT] Date:[Tue, 08 Dec 2015 16:40:27 GMT] Connection:[keep-alive] Content-Length:[908] Link:[<https://acme-v01.api.letsencrypt.org/acme/new-authz>;rel="next" <https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf>;rel="terms-of-service"] Cache-Control:[max-age=0, no-cache, no-store] Pragma:[no-cache]] 0xc8206ced80 908 [] false map[] 0xc8204cf500 0xc8204dbad0} <nil>
    20151208164027 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/directory
    20151208164027 [DEBUG] acme.api: response: &{200 OK 200 HTTP/1.1 1 1 map[Connection:[keep-alive] Strict-Transport-Security:[max-age=604800] Expires:[Tue, 08 Dec 2015 16:40:27 GMT] Date:[Tue, 08 Dec 2015 16:40:27 GMT] Replay-Nonce:[UX3ttCjAIgiv-w9vjSbAyyGsJhLncIdsTHGMpVpV-ZE] X-Frame-Options:[DENY] Cache-Control:[max-age=0, no-cache, no-store] Pragma:[no-cache] Server:[nginx] Content-Type:[application/json] Content-Length:[263]] 0xc8206cf000 263 [] false map[] 0xc8204781c0 0xc8204dbad0} <nil>
    20151208164027 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/new-authz
    20151208164027 [DEBUG] acme.api: response: &{201 Created 201 HTTP/1.1 1 1 map[Link:[<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"] Location:[https://acme-v01.api.letsencrypt.org/acme/authz/FVad8k7QoPaFXm3UUE0QEeNvLMuMribzyG8O4H30SjE] Replay-Nonce:[bmXXS6sVvGF7Z4lKYCO931qzKumkueJ6msnfUJITsxk] X-Frame-Options:[DENY] Strict-Transport-Security:[max-age=604800] Server:[nginx] Content-Type:[application/json] Content-Length:[566] Date:[Tue, 08 Dec 2015 16:40:27 GMT] Connection:[keep-alive] Expires:[Tue, 08 Dec 2015 16:40:27 GMT] Cache-Control:[max-age=0, no-cache, no-store] Pragma:[no-cache]] 0xc820668c40 566 [] false map[] 0xc820390d20 0xc8204dbad0} <nil>
    20151208164027 [DEBUG] acme.solver: attempting challenge type tls-sni-01
    20151208164027 [DEBUG] acme.solver: challenge start failed: listen tcp :443: bind: address already in use
    20151208164027 [DEBUG] acme.solver: attempting challenge type http-01
    20151208164027 [DEBUG] acme.responder: failed to listen on :80: listen tcp :80: bind: address already in use
    20151208164027 [DEBUG] acme.responder: writing webroot challenge files
    20151208164027 [DEBUG] acme.responder: http-01 self test
    20151208164027 [INFO] acme.responder: http-01 self test failed: got 200 response when doing self-test, but with the wrong data
    20151208164027 [DEBUG] acme.responder: removing webroot file /srv/app/dirname/.well-known/acme-challenge/oEu4ySycFSNtBtY4XEi3ppRN8rQiyBtH53pLCBiZCKU
    20151208164027 [DEBUG] acme.responder: removing webroot file /var/run/acme/acme-challenge/oEu4ySycFSNtBtY4XEi3ppRN8rQiyBtH53pLCBiZCKU
    20151208164027 [DEBUG] acme.solver: challenge start failed: got 200 response when doing self-test, but with the wrong data
    20151208164027 [CRITICAL] acmetool: fatal: reconcile: failed all combinations

**Comment by hlandau** [comment]
It looks like the webroot self-test is failing. acmetool tries to retrieve the challenge file using the target domain name. You can test this yourself by placing a file in the configured webroot and ensuring it's retrievable.

acmetool is successfully retrieving something (200 response code), but doesn't seem to think it's correct. Maybe your web server is changing the output, somehow. Using tcpdump or wireshark could be useful here to figure out what's going on.

(The 'failed to listen' thing is a red herring. acmetool's philosophy is to do absolutely anything that might work. The selection choice during quickstart is actually mostly fake; it only controls whether you are prompted to enter a webroot and, if you are using systemd, whether to install a unit file for the redirector.)

**Comment by mafrosis** [comment]
I destroyed the server and bootstrapped another from config (the old turn-it-off-and-turn-it-on trick) - and now it's working. Most confusing. Thanks again for putting this tool together :+1:
