### ISSUE TITLE
Provide aarch64 (ARM64) binary

### ISSUE THREAD

**Issue by klausenbusk** [hlandau/acme#38]
Hello

I have a ARM server at [Runabove](https://www.runabove.com/armcloud.xml), where I host a Mumble server. I want to "install" a validated SSL certificate. But it seems like you don't provide a aarch64 binary. I could compile it myself, but it easier just to grab a tar and extract it.

Maybe?

Regards Kristian

**Comment by hlandau** [comment]
I'll provide binaries for the next release.

**Comment by hlandau** [comment]
Oh, right, yes, the dup2 issue is why they aren't included. I'll take a look at the issue.

**Comment by klausenbusk** [comment]
I can see you released v0.0.19 which say "Add arm64 build", but there isn't attached any arm64 build?

**Comment by klausenbusk** [comment]
It seems like gox doesn't have a arm64 arch. Maybe I should open a issue?

**Comment by hlandau** [comment]
I've submitted a pull request. Once gox is updated, I can just make travis rebuild and it should show up.

**Comment by hlandau** [comment]
An arm64 build is now available.
