### ISSUE TITLE
Error compiling on ARM64 (undefined: syscall.Dup2)

### ISSUE THREAD

**Issue by klausenbusk** [hlandau/acme#40]
`src/gopkg.in/hlandau/service.v2/daemon/dupfd/dupfd-unix.go:8: undefined: syscall.Dup2`
It seems like ARM64 don't have the DUP2 syscall As started in the golang issue: https://github.com/golang/go/issues/11981

Blocking #38 

Regards Kristian

**Comment by hlandau** [comment]
Fixed to use dup3, now builds on arm64.
