### ISSUE TITLE
Rootless mode doesn’t seem to work correctly

### ISSUE THREAD

**Issue by Flink** [hlandau/acme#41]
I’m trying to use a dedicated user for acmetool. I’m specifying a custom state path, a custom hooks path and a response file but I have some problems:

- the cron task is not added to the user’s crontab
- I specified the proxy method in the response file but acmetool tries to open a webroot file somewhere it has no permissions (in /var/run/acme/acme-challenge). It shouldn’t try that.

**Comment by hlandau** [comment]
acmetool always tries all methods available to it. The method choice in the quickstart wizard is only used to determine what further questions to ask. These failures don't matter. Essentially the philosophy is to try anything that might work, do a self-test for the desired hostname and if it works, complete the challenge. So trying and failing to write to `/var/run/acme/acme-challenge` is normal and OK.

The crontab should be added. If you aren't even asked whether you want it installed, this means it's detecting that it's already installed - possibly at the system level (in `/etc/cron.d`). At any rate, you can work around this by installing the cronjob yourself, as `acmetool --batch --state=... --hooks=... reconcile`.

**Comment by Flink** [comment]
Oh ok, I let the proxy config with the port 402 instead of setting 4402 since it’s not the root user! And indeed it then works as expected.

For the crontab, indeed I have the global config, so it seems to explains. But I think acmetool should detect if the crontab installed will update the correct state path or not.

Otherwise it works, so thank you, great project and thank you for your time :)
