### ISSUE TITLE
Hard coded user os /var/run seems to make this unworkable without root/sudo

### ISSUE THREAD

**Issue by banks** [hlandau/acme#43]
Hi,

For fun of it tried to get this running on webfaction which is a great shared service that gives you a ton of control. You don't have a root account or sudo access though.

I have it setup using WEBROOT and all seems OK - i manually verified making a fake challenge file and loading it.

I got this working by manually setting `--state` and `--hooks` (as well as webroot) to be a path under my home dir.

But when I run `want` I get:

```
$ acmetool --state $HOME/acme --hooks $HOME/acme/hooks want <mydomain>
20151211122610 [ERROR] acme.responder: failed to open webroot file /var/run/acme/acme-challenge/LcjeWQJ2rMsQk0L0S1y4h0gCSguDAsESluhypLT9lOI: open /var/run/acme/acme-challenge/LcjeWQJ2rMsQk0L0S1y4h0gCSguDAsESluhypLT9lOI: no such file or directory
20151211122610 [ERROR] acme.storage: could not obtain authorization for <mydomain>: failed all combinations
20151211122610 [ERROR] acme.storage: failed to request certificate for target Target(<mydomain>;;0): failed all combinations
20151211122610 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:
error satisfying target Target(<mydomain>;;0): failed all combinations
```

Is it possible to have this temp dir configurable too such that this can work without access to `/var/run` or is the problem something else entirely?

**Comment by hlandau** [comment]
This indicates that you don't have a webroot path set. Are you sure you ran the quickstart for the same directory? $HOME/acme/conf/webroot-path should contain the configured path. If it doesn't for some reason, you can put the path in there yourself...

**Comment by banks** [comment]
I ran quickstart with `/home/banks/acme/www` as webroot and it exists and works.

I assumed this is an issue working with temp files during the process but could be wrong...

I'll try again from scratch.

**Comment by hlandau** [comment]
acmetool tries all strategies available to it to pass challenges. The mode question in the quickstart is only used to determine what questions to ask. It will always try to place files in /var/run/acme/acme-challenge, as well as any webroot directory you configure. Failure to place files in /var/run/acme/acme-challenge is normal in circumstances such as these and not indicative of an issue.

**Comment by banks** [comment]
Yep same... I see nothing in the actual webroot after this...

```
$ ls /home/banks/acme/www/.well-known/acme-challenge
$
```
```
$ cat /home/banks/acme/conf/webroot-path
/home/banks/acme/www/.well-known/acme-challenge
```

If `/var/run` is not the issue then do any of those other failures help you understand what is? I'll admit I'm not sure what to try next.

Thanks for the help by the way. Hopefully this will smooth the path for other users later not just take up your time helping me out!

**Comment by hlandau** [comment]
Challenge files are created and deleted within the scope of reconciliation. Is it still failing? You can try passing `--xlog.severity=debug` for more logging.

**Comment by banks** [comment]
Aha. debug logging helped. It seems this host has no DNS entry for the subdomain I'm trying to register. I'll figure out why (I did create it - perhaps propagation delay).

So it is actually writing files to right place, just failing to get them back due to DNS issue. Sorry for taking your time.
