### ISSUE TITLE
Add hook/notify test mode

### ISSUE THREAD

**Issue by klausenbusk** [hlandau/acme#44]
I was creating a hook script yesterday to copy and change owner of cert/privkey, so murmur (mumble) could use it.
But every time I needed test it, it required me to delete the acme/live/<domain>, so the hook script got called. I don't think that is optimal.

Regards Kristian

**Comment by hlandau** [comment]
This is a good idea.

**Comment by hlandau** [comment]
Test command in v0.0.22.
