### ISSUE TITLE
Add --no-reconcile option to want subcommand

### ISSUE THREAD

**Issue by mafrosis** [hlandau/acme#45]
I've been attempting to build a server image, but with missing certs which will be filled in by `acmetool reconcile` at boot time.

The ideal situation would be to call `acmetool want <url>` during server build, and then at server boot `reconcile` will do the rest. The key issue is that when `want` is called, the server is unable to respond to the challenge/response - it can only do that later when it's up and running.

Thoughts? I don't _think_ this will be difficult to achieve looking at the codebase, but I thought I'd open a ticket :)

**Comment by hlandau** [comment]
So basically you want something like a `--no-reconcile` option. This is trivial; I'll implement it.

In the meantime, you should note that all `want` does is drop a target file in /var/lib/acme/desired. So feel free to do that yourself. [The state directory format is documented.](https://github.com/hlandau/acme/blob/master/_doc/SCHEMA.md)

**Comment by mafrosis** [comment]
Ahh I see. Yes that's exactly what I'm after. I thought `want` was actually doing the hard work - but want actually wraps reconcile.. I should probably read the source code better next time ;)

Thanks for a great little app

**Comment by hlandau** [comment]
The flag is now available in v0.0.23.

**Comment by mafrosis** [comment]
Legend :+1: :smile:
