### ISSUE TITLE
Allow multiple domains in one cert via SAN

### ISSUE THREAD

**Issue by erichelgeson** [hlandau/acme#48]
Using Subject Alternative Name (SAN) fields in the cert you are able to specify multiple domains, eg

`example.com www.example.com web.example.com` 

can all be valid under the same certificate. Useful in the situation were ELBs can only have 1 cert.

Something like ~~ `./acmetool want example.com --sni www.example.com,web.example.com`

**Comment by hlandau** [comment]
Wait, what? The whole point is that this is already supported.

`acmetool want example.com www.example.com somethingelse.com foo.bar.xyz`

**Comment by erichelgeson** [comment]
I first did `acmetool want api.example.com` then `acmetool want example.com www.example.com` and I saw 3 dirs under `live` so I assumed (incorrectly) it was 3 distinct certs. under `../certs` it is only 2. Sorry for the confusion!

**Comment by hlandau** [comment]
Sure. By the way, if you have multiple targets (files under `desired`) and some share desired names, the priority field controls which gets targeted as the symlink in `live`. https://github.com/hlandau/acme/blob/master/_doc/SCHEMA.md#desired
