### ISSUE TITLE
Add means of cleaning up unwanted domains

### ISSUE THREAD

**Issue by adhawkins** [hlandau/acme#54]
Once you're finished with a domain, it'd be nice if there was an operation that was the opposite of 'want', that would remove all reference to that domain and it's keys / certificates in the /var/lib/acme directory.

**Comment by hlandau** [comment]
Added `unwant` command, which removes hostnames from any target files in which they appear. Target files which, as a result, have no hostnames are deleted.

**Comment by adhawkins** [comment]
I've had a quick look over the commit that references this change, and it doesn't seem to remove any keys / certificates for the domains that are no longer wanted.

My knowledge of go is almost non-existant, so it's possible I've missed it.

Or was this a deliberate decision to retain any existing keys / certificates for an unwanted domain?

Thanks

Andy

**Comment by hlandau** [comment]
I don't see any point in removing keys/certificates. The disk space they take up is negligible, and if you later decide you want to use that hostname after all, the certificate can be reused. The private key has already hit the disk and the certificate has already been issued, so there's no security benefit to deleting it; if you're concerned about security you should properly revoke it (and revocation support is TODO).

**Comment by adhawkins** [comment]
Ok. It was more a desire not to have 'old' certificates left around once they're expired / no longer used.
