### ISSUE TITLE
"make install" fails when using gvm with zsh

### ISSUE THREAD

**Issue by simonszu** [hlandau/acme#55]
Hi,

i have noticed that "make install" fails when i am using the [gvm](https://github.com/moovweb/gvm). Due to the usage of gvm, my go binary is in `$HOME/.gvm/gos/go<VERSION>/bin/go`. To make this path available in my $PATH, i am sourcing an initfile of gvm in my shell's rc-file, in my case in the .zshrc. 

Unfortunately, this does not work for acme's makefile, because this is the result of `sudo make install`:

```
       [RELOCATE]
        [DIRS]
        [GO-INSTALL]      github.com/hlandau/acme/cmd/acmetool
/bin/bash: go: Command not found.
Makefile:47: recipe for target 'all' failed
make: *** [all] Error 127
```

So, this makefile makes use of the bash-environment, and since there is no trace of the gvm environment in my bashrc, the makefile does not find the go binary and the command fails. 

I have no idea how to write a makefile or modify, since it's syntax is completely new for me, but i think it should suffice if it would execute the makefile-equivalent of `[[ -s "${HOME}/.gvm/scripts/gvm" ]] && source "${HOME}/.gvm/scripts/gvm"`, maybe at the beginning where it determines the GOPATH and the GOBIN, so when there is a gvm environment installed, its go binary will be prioritized above the system's go, or, there will be a go binary found _at all_, even when there is no system go binary installed.

**Comment by hlandau** [comment]
You could try just removing the `SHELL := /bin/bash` line. zsh should work acceptably. If you find it defaults to /bin/sh rather than /bin/zsh, maybe `SHELL := /bin/zsh`?

**Comment by simonszu** [comment]
Your suggestions would only be helpful for me. I was thinking of something universal - since i can't be the only one using acme and gvm.

**Comment by hlandau** [comment]
The makefile isn't broken. Similar issues would occur if executing a shell script with a shebang line of '#!/bin/bash' - which is a perfectly reasonable thing. If you want your PATH to be available to any shell, you should set it in .profile or something.
