### ISSUE TITLE
Error when generating certificate

### ISSUE THREAD

**Issue by adhawkins** [hlandau/acme#56]
Hi,

When I generate a certificate for a new domain, I get the following error:

admin@gently:~$ acmetool want mail.gentlyhosting.co.uk
20160105202324 [ERROR] acme.responder: failed to open webroot file /var/run/acme/acme-challenge/Gr12TmD1TtK8U36MCKt7o19UQ2ta6rZ4BTBJYgZdWm8: open /var/run/acme/acme-challenge/Gr12TmD1TtK8U36MCKt7o19UQ2ta6rZ4BTBJYgZdWm8: no such file or directory

However, the certificate generation actually succeeds. The path specified under /var/run is actually not where the challenge information is create (I've created a non-root installation, and moved the directory used to store the challenges).

The correct path is specified in /var/lib/acme/conf/webroot-path

**Comment by hlandau** [comment]
This is normal. See the WIP user guide: http://hlandau.github.io/acme/userguide.html#challenge-completion-philosophy
