### ISSUE TITLE
Support hostname-specific webroots

### ISSUE THREAD

**Issue by joneskoo** [hlandau/acme#61]
want command should accept an optional hostname-specific webroot / responder configuration.

I tried entering webroot for one site in quickstart:

    $ ./acmetool --state=$HOME/.acme/state --hooks=$HOME/.acme/hooks quickstart

It created this:

    $ cat .acme/state/conf/webroot-path ;echo
    /home/users/joneskoo/sites/HOSTNAME/www/.well-known/acme-challenge

Now when I try to request a certificate:

    $ ./acmetool --state=$HOME/.acme/state --hooks=$HOME/.acme/hooks want HOSTNAME
    20160109175123 [ERROR] acme.responder: failed to open webroot file /var/run/acme/acme-challenge/XXXXXXXXX: open /var/run/acme/acme-challenge/XXXXXXXXX: no such file or directory
    20160109175123 [ERROR] acme.storage: could not obtain authorization for HOSTNAME: failed all combinations
    20160109175123 [ERROR] acme.storage: failed to request certificate for target Target(HOSTNAME;;0): failed all combinations
    20160109175123 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred: error satisfying target Target(HOSTNAME;;0): failed all combinations

It looks to me like it's not even using the configuration I gave. I'm running non-root. As far as I can tell, want command does not support specifying web root, configuration is global.

Context: I'm looking to use acmetool on a shared hosting environment. Certificates can be loaded automatically by user. Ideally in a centrally managed, virtualhosting mode, or alternatively just documenting instructions for users to reproduce.

**Comment by hlandau** [comment]
See http://hlandau.github.io/acme/userguide#challenge-completion-philosophy
Attempting to write to `/var/run/acme/acme-challenge` is not an indication that it is not using your configured webroot path, nor is it fatal. It will try to write to `/var/run/acme/acme-challenge` and any configured webroot path, and so long as *something* works it's fine. Try passing `--xlog.severity=debug`.

**Comment by joneskoo** [comment]
@hlandau Thanks. It did write the file as configured correctly and just failed http-01 self test and this wasn't obvious without debug output and the other error confused me.

    20160109225838 [DEBUG] acme.responder: http-01 self test
    20160109225838 [INFO] acme.responder: http-01 self test failed: non-200 status code when doing self-test
    20160109225838 [DEBUG] acme.responder: removing webroot file /home/users/joneskoo/sites/HOSTNAME/www/.well-known/acme-challenge/XXXXXXX

If you don't mind, let's keep this issue about the original problem, being able to request certificates for different vhosts using different webroots. If you want, please create a new issue for this log level / self-test.

The use case in my mind includes potentially a very large number of vhosts. In any case it is necessary to support multiple webroots for this use case. I think it would be wasteful to simply drop challenges to potentially hundreds of vhosts. That's why I see it would be useful to provide hostname-specific webroot for the challenge responder.

**Comment by hlandau** [comment]
I think it's okay to drop challenges in hundreds of vhosts; UNIX filesystems are fast. But for that matter, couldn't you just symlink it or alias it in your webserver configuration for all vhosts?

In the first place, acmetool has no concept of a vhost; only targets. So maybe a target could express webroot paths. That might be possible. Something like, in a targetfile:

```
request:
  webroot-paths:
    - /...
```

**Comment by joneskoo** [comment]
Ok, I understand the philosophy a little better now, thanks! I'll have to think about it.

Global aliasing or symlink for the well-known URI might work. I have to think more what might be the best approach for a central deployment and whether that is feasible in the first place or is documentation+manual activation by user better.

I have to read more about acmetool implementation and targetfiles, I wasn't aware of that.

I don't have strong opinions at this point. I'm a bit concerned about global state directory for non-root multiuser install. It's a separate issue anyway. If you think there's nothing to implement here, feel free to close this issue and I'll re-open or open new one once I have a strong opinion.

**Comment by joneskoo** [comment]
@hlandau Given the philosophy and thinking about this for a bit, I think a shared well-known directory by configuration, proxy or symlink is sufficient and I can't think of justification for configuring this per-target any more. It's already complex enough to grasp the current feature set.
