### ISSUE TITLE
Allow distribution packaging to change default paths

### ISSUE THREAD

**Issue by joneskoo** [hlandau/acme#64]
In order to match Homebrew standard paths, I had to create a patch to change paths (https://github.com/Homebrew/homebrew/pull/47923). I don't think the formula could be accepted without conforming to standard paths. Now, patching it in various files is ugly: https://github.com/joneskoo/homebrew/commit/abbb41a880500abf952ffbeb497cc0db5fb3aea4

Please support changing paths in distribution, e.g. a single constants file.

**Comment by hlandau** [comment]
Paths in the referenced patch seem to be programmatically gnerated. What sort of actual paths are used? Would functionality similar to autotools `--prefix` be sufficient, or is something more specific necessary?

**Comment by joneskoo** [comment]
Homebrew is like ports, and can be installed to a non-default prefix.
Essentially I'd just want paths to be configurable without patching source
files. Homebrew variables explained here:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#variables-for-directory-locations

Lib dir for hooks is a mystery to me, now I put it version specific but
maybe hooks are more like etc at least on OS X as the default hook does
nothing. And based on the comment, you expect some users to edit it, but
the hook path is fixed?

Regardless, I don't think it makes sense to do a Homebrew specific change.
Instead standard packaging practices apply; what would you need for NetBSD
pkgsrc, FreeBSD ports, RedHat RPM, Debian.

Homebrew can collect and install files just fine, I didn't use the Makefile
at all, for instance. Why a change is needed in the first place is for the
paths to be reflected in man page, examples, etc. The homebrew prefix is
normally writable by non-root user (ie. the person installing the
application).

I'm not sure what docs to install, now I installed basically all; maybe the
shorter readme like under .travis would suffice? I don't know.

I think something like --prefix is the way to go, but changed in go build?

**Comment by hlandau** [comment]
`(/usr)?/lib(exec)?/foo` is the correct place for at least default system hook scripts. For example, distro-installed systemd unit files are installed to `/lib/systemd/system`. You will also find, for example, that on Linux, DHCP clients and similar often use hook shell scripts installed at some point under `/usr/lib(exec)?`. The standardization of `/usr/libexec` on redhat-style distros demonstrates the need for a place for this sort of thing.

Still, this directory is mostly suitable for "managed" files, indeed. The ability to shadow /usr/lib/acme/hooks (or wherever) to somewhere in `/etc` (or even the state directory) might make sense. Created issue #65.

As for this issue, either generic `--prefix`, `--bindir`, `--libdir`, `--localstatedir` flags could be supported, or specific overrides could be supported for the paths that acmetool needs. I think the latter is probably going to be better at this juncture. So I'll add such facilities.

**Comment by hlandau** [comment]
https://github.com/hlandau/acme/blob/dev/_doc/PACKAGING-PATHS.md

**Comment by joneskoo** [comment]
Thanks, sounds very reasonable to me. What about var/run used for
well-known challenges? I didn't see that listed. I could imagine that
common path being e.g. preconfigured or commented in nginx for example, but
it implies it's configurable in packaging.

**Comment by hlandau** [comment]
Updated: https://github.com/hlandau/acme/blob/dev/_doc/PACKAGING-PATHS.md
Will enter master soon.

**Comment by hlandau** [comment]
Merged to master. I think this completes this issue.
