### ISSUE TITLE
Do not default to staging API

### ISSUE THREAD

**Issue by joneskoo** [hlandau/acme#69]
If user skips quickstart and does want directly, acmetool does not prompt which API to use and defaults to staging. Discussed this on IRC earlier.

Either should prompt or default to LE production API in my opinion.

**Comment by hlandau** [comment]
Maybe it should prompt the user, like in the quickstart.

**Comment by hlandau** [comment]
On second thoughts, I'll just make it use the live server by default. I don't want to prompt outside of the quickstart unless absolutely necessary. v0.0.35.
