### ISSUE TITLE
[CRITICAL] acmetool: fatal: reconcile: rename /var/lib/acme/tmp/symlink.239454073 /var/lib/acme/live/HOSTNAME: invalid cross-device link

### ISSUE THREAD

**Issue by TyberiusPrime** [hlandau/acme#75]
Hello,

I'm running acemetool inside a docker, and have /var/lib/acme linked in from outside the docker to allow storage of the certificates. 

Apperantly at one point acmetool tries a hard link and fails because it would have to link across file system boundaries.
Error message: See title.

So long,
Tyberius Prime

**Comment by hlandau** [comment]
It doesn't use hardlinks. It tries to rename a symlink into place. You need to have `/var/lib/acme/live` and `/var/lib/acme/tmp` on the same filesystem.
