### ISSUE TITLE
Liberalise private key permissions to 640

### ISSUE THREAD

**Issue by hlandau** [hlandau/acme#76]
Some daemons, such as exim, don't read private keys as root. Currently, acmetool doesn't care about the owners or groups of files, but does enforce modes. By extending private key permissions to 640, this allows users to chgrp files more easily, but doesn't compromise security for the default case where files are created with UID=GID.

A temporary workaround is to chown instead. Though in either of these cases, the changes will need to be made after each invocation of acmetool, so that new keys get appropriate UIDs and GIDs. For the time being this could be done by adding or modifying a notification script. Something like this should suffice:

```
#!/bin/sh
chgrp -R DESIRED_GROUP_NAME "$ACME_STATE_DIR/keys"
chmod -R g+r "$ACME_STATE_DIR/keys"
find "$ACME_STATE_DIR/keys" -type d -exec chmod g+x '{}' ';'
```

POSIX ACLs might also be an option. Long term I should find a better solution for this.

**Comment by joneskoo** [comment]
Did you consider a non-root user whose default group has other users as
well? Is this a security issue for them? Probably not a common case but I'm
suspicious of changing the default to relaxed rather than user explicitly
requesting wide permissions.
