### ISSUE TITLE
Consider making file permissions configurable

### ISSUE THREAD

**Issue by hlandau** [hlandau/acme#77]
Following on from #76.

**Comment by joneskoo** [comment]
Maybe via targets file? If running as root, configuring uid/gid together
with mode might make sense?

I think common case for this is root acmetool + non-root daemon who needs
private key? If acmetool is non-root, the daemon would generally run as the
same user as acmetool right? Is this correct?

Is it sufficient to just support this case; chgrp to configured daemon
group with mode 0640?

Do you even attempt to check acl anyway or just enforce mode? Would acl
allowing daemon via non-posix permissions be preserved and could that be
used in place of acmetool configuration?

**Comment by hlandau** [comment]
I think ACLs won't get nuked. I'm assuming that chmod(2) doesn't override ACLs, I'm not very familiar with them. So for the time being ACLs should work.

**Comment by hlandau** [comment]
I should add this probably won't go via targets file. If you look in the storage module you'll see that permissions are enforced by glob patterns, and this is done when loading the directory, not in respect of any specific operation. So custom permissions would probably take the form of a file letting you specify different glob patterns. Maybe a file with lines to be changed, something like
```
# this replaces the entry with the same pattern in the default rules
./keys/*/privkey 0750 0640 [optional uid to enforce] [optional gid to enforce]
# this removes the entry with the same pattern in the default rules
./some-existing-entry inherit
```
