### ISSUE TITLE
Redirector/responder port is hardcoded and cannot be changed on the command line

### ISSUE THREAD

**Issue by adammw** [hlandau/acme#8]
https://github.com/hlandau/acme/blob/84675c7b1524bc65d08fd89e69ba46f6eef2c5fe/cmd/acmetool/main.go#L147

**Comment by hlandau** [comment]
This is more or less intentional. Would changing this be useful to you?

**Comment by banks** [comment]
This bit me - running on a service (webfaction) that allows custom binaries on an unprivileged port and then will proxy port 80 from public to your app. I tried to setup this way but it obviously wouldn't work as i can't bind port 80 on the shared host...

Bit of an edge case, but in general there are many good reasons to want to run something behind another reverse proxy or load balancer so setting port is useful.

**Comment by hlandau** [comment]
You can use port 4402 instead of 402, it will try to bind to both. But sure.

**Comment by banks** [comment]
In my case webfaction issues you with a port to prevent collision with other users...

**Comment by hlandau** [comment]
Aah. Okay.

**Comment by hlandau** [comment]
You can now specify additional ports to listen on in a target file:
```
request:
  challenge:
    http-ports:
      - 1234
      - 127.0.0.1:4567
```
As part of acmetool's "try anything which could possibly work" philosophy, it will still try to listen on 80/402/4402. Failure to do so is, of course, nonfatal.
