### ISSUE TITLE
Ability to Provide Custom CSR

### ISSUE THREAD

**Issue by thomaskonrad** [hlandau/acme#83]
Hi,

I have a feature request: It would be nice to have the ability to specify a custom CSR instead of having acmetool generate a new one. I'm asking for this because in order to use ACME in combination with certificate pinning (HTTP Public Key Pinning with the leaf certificate), one needs the new RSA key pair in advance because otherwise the new public key cannot be updated in the HPKP header and clients which have cached the old public key won't be able to establish a TLS connection in that case.

With the ability to specify a custom CSR, the admin can decide when to renew the RSA key pair and is therefore more flexible.

Thanks
Thomas

**Comment by hlandau** [comment]
See #58. I'd rather allow people to specify a key to reuse in the targetfile. This allows key reuse but with the existing mechanism.
