### ISSUE TITLE
Hitch support

### ISSUE THREAD

**Issue by hlandau** [hlandau/acme#87]
@denisbr So it looks like Hitch can be supported simply via s/haproxy/hitch/g. In which case I may as well rename the HAProxy support to "HAProxy/Hitch" support and make clear that it can be used for Hitch too. At the very least ask whether to install the HAProxy support if Hitch is detected. I think I'll keep the files and directories called 'haproxy', but hopefully documentation make it adequately clear that these files can be used for Hitch too. Thoughts?

**Comment by denisbr** [comment]
Yes, I was working on getting a working hitch hook going on friday, so when
I discovered your HAproxy support today I was happy.
Fine by me either way actually, I think keeping them as haproxy but
detecting hitch in the quickstart and the hook script would be great.
On Mon, 25 Jan 2016 at 23:13, Hugo Landau <notifications@github.com> wrote:

> @denisbr <https://github.com/denisbr> So it looks like Hitch can be
> supported simply via s/haproxy/hitch/g. In which case I may as well rename
> the HAProxy support to "HAProxy/Hitch" support and make clear that it can
> be used for Hitch too. At the very least ask whether to install the HAProxy
> support if Hitch is detected. I think I'll keep the files and directories
> called 'haproxy', but hopefully documentation make it adequately clear that
> these files can be used for Hitch too. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hlandau/acme/issues/87>.
>
-- 
Denis Brækhus Senior Engineer | Varnish Software AS
Cell: +47 48047724
We Make Websites Fly!
www.varnish-software.com

**Comment by denisbr** [comment]
@hlandau Thanks, very nice to have hitch support!
