### ISSUE TITLE
acmetool not responding in proxy mode

### ISSUE THREAD

**Issue by jsonnull** [hlandau/acme#9]
I have acmetool configured via quickstart to run in proxy mode. When I start acmetool, my nginx server access logs show a request from Let's Encrypt for the challenge and the error log is not showing an error, but acmetool hangs and provides no output. How can I find out what's going wrong here?

**Comment by hlandau** [comment]
What does `sudo netstat -ntlp` show for ports 402, 4402?

**Comment by hlandau** [comment]
Also, please reproduce this and send SIGQUIT to the process to get a stack trace.

**Comment by hlandau** [comment]
This was probably issue #10, which is now fixed. The fix is in master. I'll push a new release v0.0.11. Let me know if this resolves the issue.
