### ISSUE TITLE
Reduce renewal margin

### ISSUE THREAD

**Issue by hlandau** [hlandau/acme#93]
Currently the renewal margin is 1/3rd of the certificate validity period or 30 days, whichever is lower. I should change the limit to something like 14 days, since it's currently excessive.

**Comment by w00kie** [comment]
Hello, maybe you should update the readme so it matches the coded behavior.

By the way, LE just sent me an email warning me one of my certs will expire in 19 days (why the odd number? I do not know). If everyone receives such an email, a lot of people are going to come and look at their acme install and wonder why it's not renewing.

**Comment by hlandau** [comment]
I'll revert this change.
