### ISSUE TITLE
acmetool will not revoke a certificate which is not the subject of any target?

### ISSUE THREAD

**Issue by joneskoo** [hlandau/acme#99]
I played for a bit with revoke on the staging api.

Looks like when I touch a live/$HOSTNAME/revoke and then run acmetool reconcile, it will revoke the cert but also get a replacement cert at the same time. This was a bit confusing to me as after revoke, the acmetool status showed the now-valid new cert (and there's no timestamp or anything so only indication is changed random id).

If I unwant the cert, touch /revoke and run reconcile, nothing happens. acmetool will not revoke an unwanted target. Is this intentional?

There's no command for revoke, where other clients like lego have a simple command for revoke.

**Comment by hlandau** [comment]
There should be a revoke command: https://github.com/hlandau/acme/blob/master/cmd/acmetool/main.go#L89

Automatically getting a new certificate after revoking one is the intended behaviour. acmetool always tries to satisfy its targets. I appreciate that this may be somewhat confusing. But think about it like this - if it's *possible* for you to get a new certificate after revoking the old one, but you don't want it to be possible, you have bigger issues. If it fails, it's inconsequential.

If an unwanted certificate doesn't get revoked, this is absolutely a bug.

**Comment by joneskoo** [comment]
You are correct, I just missed the command. And revoking a unwanted cert does work after all, I just re-checked it. I was just confused with the cert ids and the new cert being acquired.

So I believe everything works as designed, and it was just confusing me.
